### ISSUE TITLE
any public node for klay?

### ISSUE THREAD

**Issue by leverwwz** [klaytn/klaytn#1019]
if my wallet need to connect the node ,  which node i should use ?

**Comment by aidan-kwon** [comment]
@leverwwz Sorry for the late response. 
Currently, GroundX doesn't operate any public nodes for Cypress Mainnet. 
You need to operate your own node or you can use KAS (Klaytn API Service) instead.
(KAS has a free plan for light users. Check https://www.klaytnapi.com/ko/landing/main )
