### ISSUE TITLE
[Announce] intel mac go1.17 syscall error fix

### ISSUE THREAD

**Issue by yoomee1313** [klaytn/klaytn#1059]
A syscall error occurred on intel mac when using an out-of-date `go sys` library in go 1.17. This can be solved by updating the `go sys` library to the latest version.

The current dev branch already has updated to the latest `go sys` library, so if you use dev branch, you will not have the above problem. Alternatively, you can update directly though the `go get golang.org/x/sys@master` command.

Finally, this change will be included in klaytn v1.7.1 and later versions.

For more detailed information, please refer to the following PR and issue: https://github.com/klaytn/klaytn/pull/1048, https://github.com/golang/go/issues/45702.

**Comment by aidan-kwon** [comment]
Close this announcement since the fix is merged into the both of dev and master branches
