### ISSUE TITLE
addVote api improvement - vote value validation logic improvement

### ISSUE THREAD

**Issue by mckim19** [klaytn/klaytn#1107]
**Describe the solution you'd like**
vote value validation logic improvement

**Additional context**
AS-IS
```
> governance.vote("istanbul.committeesize", 0)
"Your vote was successfully placed."
>
```
TO-BE
```
> governance.vote("istanbul.committeesize", 0)
Error: Your vote couldn't be placed. Please check your vote's key and value
    at web3.js:3276:20
    at web3.js:6450:15
    at web3.js:5214:36
    at <anonymous>:1:1
>
```

**Comment by jiseongnoh** [comment]
Is it possible to keep the committee size proportional to total consensus nodes?

**Comment by mckim19** [comment]
> It is not automatically adjusted. Committee has to make a consensus to modify the committee size of total consensus nodes by voting of governance protocol.
