### ISSUE TITLE
Can not use klaytn client to dial with websocket

### ISSUE THREAD

**Issue by vaigay** [klaytn/klaytn#1111]
**Describe the bug**
I always get error "bad status" when dial.

**Expected behavior**
Connection made successfully

**Attachments**
Here is my code

````
func main() {
	url := "wss://KASKZCTSDT07NI1PM54OKL85:nPFDFf1Qh3Zy5VfNmYwl3WV_Vq_R_Dmo3cBtncbP@node-api.klaytnapi.com/v1/ws/open?chain-id=1001"
	ctx := context.Background()
	c, err := client.Dial(url)
	if err != nil {
		log.Fatal("Error when dial: " + err.Error())
	}
	headSink := make(chan *types.Header, 2)
	headerSubscription, err := c.SubscribeNewHead(ctx, headSink)
	if err != nil {
		log.Fatal("Error when subscribe Header: " + err.Error())
	}
	select {
	case ev := <-headSink:
		log.Printf("New block header: %v", ev.Number)
	case err := <-headerSubscription.Err():
		log.Printf("Error while subcription: %v", err)
	}
}
````

**Environment (please complete the following information)**
 - Klaytn version `$ 1.7.3`
 - go version `$ 1.17.5`
 - Ubuntu/20.04

**Additional context**

`wscat -c wss://KASKZCTSDT07NI1PM54OKL85:nPFDFf1Qh3Zy5VfNmYwl3WV_Vq_R_Dmo3cBtncbP@node-api.klaytnapi.com/v1/ws/open?chain-id=1001` work fine.

Feel free to take my url for testing.

**Comment by aidan-kwon** [comment]
Sorry for the late response.

When I test ws connection with your code, I had the same issue you remarked but it worked with Klaytn nodes such as `wss://api.baobab.klaytn.net:8652`. It seems KAS's problem. Could you report this problem to KAS help center, https://support.klaytnapi.com/hc/en-us ?

**Comment by vaigay** [comment]
@aidan-kwon 
I was debugging the klaytn client and found that in my header request there is no authorization token. Response status is 401
`wss://api.baobab.klaytn.net:8652` this url work fine. Thanks for your support

**Comment by aidan-kwon** [comment]
@vaigay Yes, you are right. Current ws client cannot set `authorization` header. And, it seems that another websocket protocol issue to connect KAS. As Ethereum did before, we are also considering websocket library update (https://github.com/ethereum/go-ethereum/pull/19866 https://github.com/ethereum/go-ethereum/pull/17699 ). I will hurry up the development. 
Thank you for the report!

**Comment by cnkarz** [comment]
I had the same issue and it worked when I replaced the URL with the one you provided. However, now I don't receive event logs from contracts. 
Previously, I forked `geth` and used your RPC URL with modified `SubscribeFilterLogs` and I was able to receive events.

**Comment by aidan-kwon** [comment]
@cnkarz Did you use KAS endpoint when you experienced the issue? I found out that KAS doesn't provide subscription data when `geth` websocket client is used (precisely when `eth_subscribe` is requested instead of `klay_subscribe`. I reported the issue to the KAS team and they will fix the issue soon (Hopely in this month).

**Comment by cnkarz** [comment]
I used KAS endpoint with modified `geth` which called `klay_subscribe`. `SubscribeFilterLogs` was successful.
Then I used `wss://api.baobab.klaytn.net:8652` with klaytn library and `SubscribeFilterLogs` doesn't work.

**Comment by JayChoi1736** [comment]
solved by https://github.com/klaytn/klaytn/pull/1652
