### ISSUE TITLE
Test for supporting eth namespace APIs and new TxTypes

### ISSUE THREAD

**Issue by jimni1222** [klaytn/klaytn#1135]
To support compatibility with ethereum, we need to support eth namespace APIs and new ethereum txs.
So to make sure those newly implemented features works, test code should be implemented.

This issue dependent with https://github.com/klaytn/klaytn/issues/1128 task.

- [x] Implement eth namespace API unit test (This will be merged with implementations in below PRs).
  - #1088 
  - #1093 
  - #1121
  - #1123 
  - #1124 
  - #1127 
  - #1129 
  - #1130
  - #1134
  - https://github.com/klaytn/klaytn/pull/1172
- [x] Modify to return ethereum tx type with eth namespace read tx APIs.
  - https://github.com/klaytn/klaytn/pull/1172
- [x] Implement eth namespace API read test with [rpc-tester](https://github.com/Krustuniverse-Klaytn-Group/rpc-tester).
- [x] Implement eth namespace API tx write test with locust-tester.
- [x] Implement klay namespace API tx write test with locust-tester.
- [x] Modify eth tx test in locust to check tx type in receipt.
- [x] Modify locust test to use baseFee.

@aeharvlee I created an issue for testing, so you can freely modify or add contents what you need to manage for this task.

**Comment by kjhman21** [comment]
@jimni1222 Please check items if they are done.
