### ISSUE TITLE
[Governance] addvalidator problem

### ISSUE THREAD

**Issue by jeongkyun-oh** [klaytn/klaytn#1143]
**Describe the bug**
The problem is that the size of council is decreased right after adding a validator.

```
> governance.vote("governance.addvalidator", "0x36ff2aa21d5c6828ee12cd2bc3de0e987bc0d4e7")
"Your vote was successfully placed."
> klay.getCouncilSize()
29
> klay.getCouncilSize()
30
> klay.getCouncilSize()
29
```

**How to reproduce**
1. Vote `removevalidator` with an address which is not added to validators yet
2. Vote `addvalidator` which is tried to remove in previous step

**Expected behavior**
I think it should prohibit from removing a validator which is not yet added.

**Additional context**
Another comment is that a vote should have timeout, but now it is not.

**Comment by aidan-kwon** [comment]
Closed via https://github.com/klaytn/klaytn/pull/1367
cc @ian0371
