### ISSUE TITLE
Tests for v1.8.0

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1146]
Klaytn v1.8.0 will introduce a lot of change in Cypress network, so this version needs to be tested more carefully. 

- [x] Define test cases 
- [x] #1201 @yoomee1313
- [x] #1181 @yoomee1313 
- [x] #1196 @aidan-kwon 
- [x] #1198 @aidan-kwon 
- [x] #1199 @aidan-kwon @ian0371 
- [x] #1197  @yoomee1313
- [x] #1182 (~3/4) @jeongkyun-oh 
- [x] #1192 (~3/4) @sirano11 
- [x] #1222 @yoomee1313

**Comment by kjhman21** [comment]
Everything is done now. Closing...
