### ISSUE TITLE
Add an option to skip transaction execution while on sync

### ISSUE THREAD

**Issue by ghost** [klaytn/klaytn#1147]
There are five steps for a node syncing blockchain from scratch.

1. Getting blocks from peers
2. Verify block headers
3. Execute every transactions with go EVM compiler ( Every possible lag would happen here )
4. Calculate root hash
5. Commit snapshot to disk

By disabling the transaction execution for initial sync or lighter clients that only need state data to serve DApps will reduce the hardware requirements for nodes and save more CPU resources ( More than 90% ) which will lead to faster sync.

Reference) Diffsync from BSC https://github.com/binance-chain/bsc/pull/376 - does light sync for initial download, and returns back to full node sync.

**Comment by 0xAyanami** [comment]
cc @jeongkyun-oh

**Comment by 0xAyanami** [comment]
Erigon has also optimized initial sync similar to this https://github.com/ledgerwatch/erigon/blob/devel/eth/stagedsync/README.md
