### ISSUE TITLE
Distinguish whether error is consensus error or vmError occurred during EVM execution.

### ISSUE THREAD

**Issue by aeharvlee** [klaytn/klaytn#1162]
During state transition, Ethereum distinguishes whether error is consensus error or vmError occurred during EVM execution. 
For this Ethereum developed [ExecutionResult](https://github.com/ethereum/go-ethereum/blob/fb3a6528cfa49f623570575c4fe9e8a716cfcdf7/core/state_transition.go#L82-L88).

This feature looks great for improving DX(Development Experience) Because developers can intuitively understand where the error is coming from.

Please take a look below examples.

When use Call or EstimateGas
**Test with revert situation(Call function required owner from address which is not owner)**
**Klaytn As-Is**
```shell
> klay.estimateGas({from: "0x3753f5bf8cCA929EeeB4B74F200dfc6375ad5444", to: "0xbe3892d33620be5aca8c75d39e7401871194d290", data: "0xa6f9dae1000000000000000000000000ca7a99380131e6c76cfa622396347107aeedca2d"})


Error: gas required exceeds allowance or always failing transaction
    at web3.js:3278:20
    at web3.js:6805:15
    at web3.js:5216:36
    at <anonymous>:1:1
```

**Ethereum**
```shell
> eth.estimateGas({from: "0xca7a99380131e6c76cfa622396347107aeedca2d", to: "0x27a110C35BA478034d7F874C89787E0FE587f65F", data: "0xa6f9dae1000000000000000000000000ca7a99380131e6c76cfa622396347107aeedca2d"})
Error: execution reverted: Caller is not owner
	at web3.js:6357:37(47)
	at web3.js:5091:62(37)
	at <eval>:1:16(10)
```

Related PR: https://github.com/klaytn/klaytn/pull/1134

cc. @aidan-kwon @jimni1222 @sirano11

**Comment by jimni1222** [comment]
Is this closed??

**Comment by yoomee1313** [comment]
The errors are clearly distinguished by next PRs.
* https://github.com/klaytn/klaytn/pull/1408
* https://github.com/klaytn/klaytn/pull/1763
