### ISSUE TITLE
v1.8.0 QA - New API tests 

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1199]
NOTE: These tests should be done through both HTTP and Websocket

Comparing `eth` API return formats with Ethereum API returns 
- [x] Check correction values of `Block`, `Transaction`, `Receipt` whether it is the same with the design document
- [x] Compare valid API returns' format with geth API returns' format with all `eth` APIs
- [x] Compare invalid API returns' format with geth API returns' format with all `eth` APIs

Check functionality of new `klay` APIs 
- [x] klay_createAccessList
- [x] klay_maxPriorityFeePerGas
- [x] klay_feeHistory

The following parameters should be considered in the test
- For "blockNumber", `0`, `bigger than latest blockNumber`, `numbers can/cannot be divided by 128`, `latest`, `pending` 
- For all parameters can be left out, left out each parameter value
- For "Hash", `Exsting value`, `Non-exting value`
- TBU

**Comment by aidan-kwon** [comment]
`eth` API lists: https://docs.klaytn.com/dapp/json-rpc/api-references/eth
RPC test tool: https://github.com/Krustuniverse-Klaytn-Group/rpc-tester

**Comment by ian0371** [comment]
For ground truth `eth` APIs, I will use infura API on the Ropsten network.

**Comment by aidan-kwon** [comment]
There are some differences in error message details, but it's not necessary things we need
