### ISSUE TITLE
v1.8.0 QA: regular tests (rolling update, ...) (~2/26)

### ISSUE THREAD

**Issue by yoomee1313** [klaytn/klaytn#1201]
## Test Result

* RPC - **2 tc failed, others passed**
  - tc1: test_debug_traceblock_RPC_error_wrong_value_param
    - purpose: expect error when calling `debug_traceblock` with a wrong value parameter
    - expected result: -32000, `could not decode block: rlp: element is larger than containing list`
    - real result:          -32000,  `could not decode block: rlp: value size exceeds available input length`
  - tc2: test_klay_newfilter_RPC_error_wrong_type_param
    - purpose: expect error when calling `klay_newfilter` with a wrong value parameter
    - expected result: `invalid argument 0: hex string without 0x prefix`
    - real result:          rpc call succeed. null is returned.
* WS - **PASS**
* Caver-js - **PASS**
* Caver-java - **PASS**
* Governance - **PASS**
* Reward - **PASS**
* Rolling-update - **PASS**

**Comment by aidan-kwon** [comment]
Two RPC test case failures have happened because of the invalid expected value of the tester. 
The actual results of test cases are the real values it should be returned. 
I fixed the tester in https://github.com/Krustuniverse-Klaytn-Group/rpc-tester/pull/40
