### ISSUE TITLE
Update SimulatedBackend to handle test cases for eth namespace APIs

### ISSUE THREAD

**Issue by aeharvlee** [klaytn/klaytn#1204]
As we add various eth namespace APIs for [v1.8.0](https://github.com/klaytn/klaytn/milestone/3), we need to update SimulatedBackend to make various tests for newly added `eth` namespace APIs.

Most of APIs uses already implemented parts in Klaytn or returns dummy and fixed values, but some APIs (eth_call, eth_estimateGas, eth_sendTransaction, or we can add more) have many changes and very important for user.

It would be good to make test cases in various situations using SimulatedBackend to facilitate maintenance of newly added APIs.

cc. @aidan-kwon @jimni1222 @sirano11

**Comment by yoomee1313** [comment]
We use [klaytn-rpc-tester](https://github.com/klaytn/klaytn-rpc-tester) to do tests on various apis.
