### ISSUE TITLE
Anyway to limit klaytn memory consuming?

### ISSUE THREAD

**Issue by manbobo2002** [klaytn/klaytn#1216]
**Describe the bug**
klaytn node is full of memory (64GB RAM already) so that we even cannot ssh the instance, need to restart

**How to reproduce**
enable web socket and then keep doing requests

**Expected behavior**
memory should be able to control

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - Klaytn version or git revision that exhibits the issue `$ ken version`
 Klaytn v1.7.3+acae89350c

 - OS and its version [e.g. macOS/10.14]
debian 10

![Screenshot from 2022-03-04 10-17-03](https://user-images.githubusercontent.com/25196415/156686821-18b0fc79-c1f3-4b14-8bca-a491776c4757.png)

**Comment by aidan-kwon** [comment]
Thank you for the report. 
It seems that memory usage of json codec used for HTTP/WS server is not controlled. 
We gonna work on this issue at Klaytn 1.9.0.

Before the enhancement, you can try to reduce the trie node cache (the largest cache in Klaytn) size by adding `--state.trie-cache-limit 10240` in the `ADDITIONAL` field of `kend.conf`. The option explicitly sets trie node cache size that helps block processing speed, but I think 10GB is okay in most cases. Without the option, the cache size is set depending on the physical memory size (In your case, 30% of 64GB). 
It is not the solution for the issue, but it will reduce the base memory usage of the Klaytn node.

**Comment by bert2002** [comment]
Hi, we just setup `1.8.4` on testnet and we run constantly into memory leaks again with the same setup that worked before from `1.8.3`. Any changes that got introduced for websockets?

**Comment by yoomee1313** [comment]
Assuming most of the api call is not a debug api which consumes a lot of memory, this problem is solved by the following PR https://github.com/klaytn/klaytn/pull/1650.

I'll close this issue for now. If your problem not solved, please reopen this issue.

**Comment by yoomee1313** [comment]
v1.10.0 rpc memory would be handled especially when most calls are getBlock.

v1.9.1
<img width="249" alt="v1 9 1-getBlockByNumber(res)" src="https://user-images.githubusercontent.com/64360042/197959035-122373a7-c8a3-445d-9218-1ea5e917f1d7.png">
v1.10.0
<img width="249" alt="image" src="https://user-images.githubusercontent.com/64360042/197959889-5bbca4dd-6f6e-4d22-97e8-9c8fd1f58f34.png">
