### ISSUE TITLE
Compile and test Klaytn w/ golang 1.17.8 

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1237]
`make test` fails when it is compiled w/ golang 1.16 or 1.17. 
Fix test failures and make Klaytn compilable w/ the latest version of golang

**Comment by kjhman21** [comment]
@aidan-kwon Please take this item to protocol part. :) I just removed interface project.

**Comment by aidan-kwon** [comment]
#1322 #1315 #1313 #1312 ㅗㅁㄴ ㄱ대닢ㄷㅇ 소ㅑㄴ ㅑㄴ녇
