### ISSUE TITLE
Apply transaction aging for more fair transaction processing 

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1238]
Since Klaytn makes a block with randomly selected transactions, some users are deploying massive transactions to get a faster order than others. To provide a more efficient way to get priority in transaction order in a fair way, Klaytn can adopt transaction aging for block generation and transaction propagation 

- https://github.com/klaytn/klaytn/issues/1274
  Refer to https://github.com/ethereum/go-ethereum/pull/21358
- https://github.com/klaytn/klaytn/issues/1275

**Comment by aidan-kwon** [comment]
@sirano11 Can I close this issue?

**Comment by sirano11** [comment]
@aidan-kwon 
Of course. Please close this issue.
