### ISSUE TITLE
Incorrect parsing

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn#1272]
[This comparison](https://github.com/klaytn/klaytn/blob/dev/build/rpm/etc/init.d/kcnd#L221) is always false due to the mistake in variable notation. It seems not used in another [place](https://github.com/klaytn/klaytn/blob/dev/build/packaging/linux/bin/kcnd). Please take a look if it is intentionally unused or missing by mistake. If the latter, the incorrect parsing above should be fixed.

**Comment by aidan-kwon** [comment]
The comparison looks like a mistake. I think we need to fix it.
The difference between `rpm` script and `linux` script for options parsing is another issue we should maintain. Can you add missing options in those scripts?

**Comment by hyunsooda** [comment]
Closed via #1273
