### ISSUE TITLE
Implement debug_traceBlockByRange

### ISSUE THREAD

**Issue by junmoDev** [klaytn/klaytn#1276]
Dear Klaytn team,

Could you implement range version of debug_traceBlockByNumber like klay_getBlockWithConsensusInfoByNumberRange at least for fastCallTracer?

Thanks,
Junmo

**Comment by aidan-kwon** [comment]
@kjhman21 I think the suggested API helps Klaytn services that use internal transaction data such as Scope and (maybe) Crypto Exchanges. How about adding it to v1.9.0 milestone as an interface project item? 
We need to consider the maximum response size of RPC server library when we implement the API.

**Comment by kjhman21** [comment]
@junmoDev Thanks for filing an issue. Also please note that you can also contribute it if you are interested in. Thanks.

@aidan-kwon Okay I will talk with interface guys.

**Comment by aidan-kwon** [comment]
@junmoDev `debug_traceBlockByNumberRange` have been implemented in v1.9.1. Please, check [this release note](https://github.com/klaytn/klaytn/releases/tag/v1.9.1).
