### ISSUE TITLE
Is it okay to set bridge as a non contract account?

### ISSUE THREAD

**Issue by ehnuje** [klaytn/klaytn#1278]
Below is from ERC721ServiceChain.sol
It checks if the given address is contract in its constructor.
However, it does not check whether it is a contract or not when called by `setBridge` function. 

Is it intended?

```
contract ERC721ServiceChain is ERC721, Ownable {
    address public bridge;

    constructor(address _bridge) internal {
        if (!_bridge.isContract()) {
            revert("bridge is not a contract");
        }

        bridge = _bridge;
    }

    function setBridge(address _bridge) public onlyOwner {
        bridge = _bridge;
    }

    function requestValueTransfer(uint256 _uid, address _to, bytes calldata _extraData) external {
        transferFrom(msg.sender, bridge, _uid);

        IERC721BridgeReceiver(bridge).onERC721Received(msg.sender, _uid, _to, _extraData);
    }
}
```

**Comment by hyunsooda** [comment]
Hi @ehnuje,

That seems a mistake in my view. The `bridge` address must be a contract address that implements the corresponding transfer functions for ERC-20, ERC-721, KIP-7, KIP-17, and KLAY. I think the same check should be applied to the `setBridge` function.  Let me post a fix once it's confirmed.

**Comment by kjhman21** [comment]
@KimKyungup Could you please share your opinion?

**Comment by ehnuje** [comment]
> 

@hyunsooda Thanks! If so, `ERC20ServiceChain.sol` should be updated, too.

**Comment by KimKyungup** [comment]
As @hyunsooda said, it is just mistake. It is better to check if it is a contract in `setBridge()`.

**Comment by kjhman21** [comment]
@henry-will Please assign someone to do this.

**Comment by hyunsooda** [comment]
I think KIP-13 seems needed as well since the `setBridge()` function checks only the account type, not the bridge interface that implemented corresponding transfer functions.

**Comment by kjhman21** [comment]
Then, let's go for it. ;) It might be good if we have a different PR for this, though.
