### ISSUE TITLE
Make a test case for ServiceChain

### ISSUE THREAD

**Issue by kjhman21** [klaytn/klaytn#1281]
Make a test case to check the below case:

1. ServiceChain pending tx is full, but they cannot be processed (like nonce is too high?)
2. based on this situation, check out how anchoring and value transfer works.
3. If we found an issue, need to find a solution for this.

@henry-will Please take this into consideration. I will describe this more in the meeting.

**Comment by aidan-kwon** [comment]
@henry-will Is there any progress afterwards?

**Comment by henry-will** [comment]
@aidan-kwon No, there is not yet. But I have a plan to maintain a long term AWS instance and testing some case for increasing nonce, using memories or using tx pool with such AWS instance. 
This issue is not to-do list, but is a back-log currently.

**Comment by hyunsooda** [comment]
The pending txs can be stacked if the corresponding receipt of the value transfer tx does not arrive from the counterpart chain (if it is received, that tx is removed from the bridge tx pool). If a bridge node is down a long time, the pending txs can have the max size and do not accept a new bridge tx until the preceding txs are removed. Likewise, this is an extremely rare case (not expected).
However, the dropped tx can be eventually executed by value transfer recovery (VTR) anyway. 

There is another consideration for the security aspect. By the current VTR implementation, a DoS attack is easily possible (tested) as well as a gas exhaustion attack. #1565 is aware of them and has fixed commits.

**Comment by sjnam** [comment]
no longer discussion
