### ISSUE TITLE
Would it be better to print the location of an imported account?

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn#1300]
The account import takes the user's private key with the data directory to be located imported keystore directory. It seems better to explicitly print the location of the imported account. If the data directory is not explicitly given in the cmd argument, then it would be imported to the default location (i.e.,`~/.kcn`, `~/.ken`, and so forth). It would save time for the reasoning why the account is not actually imported when they forget to give a data directory argument or there's a typo of the data directory argument. If you guys think it seems helpful, I'll upload PR.

**Comment by kjhman21** [comment]
@hyunsooda Yeah, why not? You can also upload PR as you want and then we can discuss the usefulness and necessity in the PR. :)

**Comment by henry-will** [comment]
Thanks.
