### ISSUE TITLE
Chaindatafetcher minor update

### ISSUE THREAD

**Issue by jeongkyun-oh** [klaytn/klaytn#1302]
Range fetching API should be updated with meaningful parameters. Currently, the parameters are magic number (for blockground, tracegroup, or allgroup). This should be updated.

- https://github.com/klaytn/klaytn/pull/1587

---

Chaindatafetcher message is better to update to make them consistent with the result of `GetBlockWithConsensusInfo` api.

The difference between kafka result and the api result is:
- committee members (kafka include all council members, not only committee members)
- round info (newly updated)
- original proposer info (newly updated)

Block validator list (or council members) may be included as well if necessary.

- https://github.com/klaytn/klaytn/pull/1611

**Comment by aidan-kwon** [comment]
There is a requirement from consumer users. They want to get information about the deployed transaction's KIP/EIP implementation whether it implemented KIP7, ERC20, or other specifications. 
It is not mandatory, but let's consider this too.

**Comment by jeongkyun-oh** [comment]
Test for this PR

- version: version: Klaytn v1.10.0+5025e0f61e

```
> chaindatafetcher.startRangeFetching(90000000, 90001000, 2)
Error: the request type is not valid
    at web3.js:3278:20
    at web3.js:6810:15
    at web3.js:5221:36
    at <anonymous>:1:1

> chaindatafetcher.startRangeFetching(90000000, 90001000, 48)
null
> chaindatafetcher.startRangeFetching(90000000, 90001000, 1)
Error: the request type is not valid
    at web3.js:3278:20
    at web3.js:6810:15
    at web3.js:5221:36
    at <anonymous>:1:1

> chaindatafetcher.startRangeFetching(90000000, 90001000, 48)
null
> chaindatafetcher.startRangeFetching(90000000, 90001000, "block")
null
> chaindatafetcher.startRangeFetching(90000000, 90001000, "trace")
null
> chaindatafetcher.startRangeFetching(90000000, 90001000, "all")
null
> chaindatafetcher.startRangeFetching(90000000, 90001000, "wrong")
Error: the request type should be 'all', 'block', 'trace', or uint type
    at web3.js:3278:20
    at web3.js:6810:15
    at web3.js:5221:36
    at <anonymous>:1:1
```

**Comment by jeongkyun-oh** [comment]
Test for this PR

- version: Klaytn v1.10.0+5025e0f61e
- checked newly added/original fields with Kafdrop.

<img width="1271" alt="스크린샷 2022-12-01 오후 4 55 20" src="https://user-images.githubusercontent.com/45347815/204996976-07873178-6506-4026-b1b4-0437a46fc0fd.png">
