### ISSUE TITLE
Add metric for servicechain

### ISSUE THREAD

**Issue by hqjang-pepper** [klaytn/klaytn#1319]
Currently, there is some metrics for ServiceChain in klaytn.
It looks like we need to collect some additional metrics.
Add more metrics for ServiceChain to check status via monitoring tool, such as Grafana

**Comment by hqjang-pepper** [comment]
@nohkwak

**Comment by aidan-kwon** [comment]
@hqjang-pepper Is there any progress on this issue?

**Comment by hqjang-pepper** [comment]
Yes, there was fix in both klaytn and klaytn-deploy repository.
https://github.com/klaytn/klaytn/pull/1572
https://github.com/klaytn/klaytn-deploy/pull/5
