### ISSUE TITLE
Make new flag groups for bridges

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1324]
We have flag group categories for each service node type, but some flags depend on the bridge type rather than the node type. For example, EN is not a service node type but it can enable MainBridge and other MainBridge-related options. 

And the new flag group depending on the bridge can reduce the mistake that can happen when a developer adds a new bridge-related flag.

Similar link: https://github.com/klaytn/klaytn/pull/1287

**Comment by henry-will** [comment]
Thank your comment. ServiceChain should check the scope of servicechain node and bridge. They will separate main nodes from servicechain nodes.
What about the ServiceChain prefix convention of this PR #1287 changed

**Comment by aidan-kwon** [comment]
Related code: https://github.com/klaytn/klaytn/blob/dev/cmd/utils/nodecmd/nodeflags.go

**Comment by hqjang-pepper** [comment]
I checked all the cil.Flags that nodes are using. 
There are few bridge related flags, and there are not many flags included in common. 
So I'm not sure this work is really needed.
Instead, maybe we can make KAS or chaindatafetcher related flags as a single flag group, respectively. How do you think?

cc. @aidan-kwon
