### ISSUE TITLE
Tests for v1.8.4

### ISSUE THREAD

**Issue by kjhman21** [klaytn/klaytn#1331]
- [x] ServiceChain tests @henry-will @hyunsooda @hqjang-pepper 
  - backward compatibility for ERC-20 between old EN and new SEN
  - check if new command line options work normally

**Comment by henry-will** [comment]
backward compatibility for ERC-20 and ERC-721 between old EN and new SEN
- [ ] condition : [Subbridge] New node + New contract, [Mainbridge] New node + New contract
   Result : OK
- [ ] [Subbridge] New node + New contract, [Mainbridge] New node + New contract
   Result : OK
- [ ] [Subbridge] New node + New contract, [Mainbridge] New node + New contract
   Result : OK
- [ ] [Subbridge] New node + New contract, [Mainbridge] New node + New contract
   Result : OK
- [ ] [Subbridge] New node + New contract, [Mainbridge] New node + New contract
   Result : OK

**Comment by henry-will** [comment]
test Contract API
- [ ] call getParentBridgeContractBalance
- [ ] call getChildBridgeContractBalance

**Comment by henry-will** [comment]
test config options

- [ ] set VTRECOVERY options to 1 or 0
   result : changed VTRECOVERY
- [ ] set SC_VTRECOVERY options  to 1 or 0
   result : changed SC_VTRECOVERY
- [ ] set SC_VTRECOVERY_INTERVAL options
   result : changed SC_VTRECOVERY_INTERVAL

**Comment by henry-will** [comment]
test servicechain gas limit options

- [ ] set SC_DEFAULTGASLIMIT
   result : changed ServiceChainOperatorGasLimit
- [ ] change DefaultBridgeTxGasLimit
- [ ] call getBridgeOperatorGasLimit
- [ ] call setBridgeOperatorGasLimit

**Comment by henry-will** [comment]
- [ ] check log when account imported

**Comment by henry-will** [comment]
test remote_backend.go 

- [ ] check error status when context error occurs

**Comment by henry-will** [comment]
- [ ] set SC_KAS_ANCHOR_REQUEST_TIMEOUT in kscnd
   result : changed KASConfig.RequestTimeout
- [ ] set SC_KAS_ANCHOR_REQUEST_TIMEOUT in kspnd
   result : changed KASConfig.RequestTimeout
- [ ] set SC_KAS_ANCHOR_REQUEST_TIMEOUT in ksend
   result : changed KASConfig.RequestTimeout

**Comment by henry-will** [comment]
> test servicechain gas limit options

**Comment by JayChoi1736** [comment]
**Regular QA Test**

- [ ] Rolling Update test: 
- [x] RPC/WS test: **PASS**
 - [rpc](https://github.com/klaytn/klaytn/files/8700110/KlaytnTestReport_2022-05-14_14-04-07.pdf)
 - [ws](https://github.com/klaytn/klaytn/files/8700111/KlaytnTestReport_2022-05-14_14-09-39.pdf)
- [ ] Governance test: 
- [ ] Reward test: 
- [ ] Caver js/java test: 
- [x] Sync test (discuss with @aidan-kwon)
  - Node Configuration
    - en0(c5.2xlarge, 6T): sync from 0 to ~
    - en1(c5.2xlarge, 6T): sync from 52007592 to ~
- [ ] Load test (discuss with @aidan-kwon)
  - [ ] Stress: .
  - [ ] Reliability: .
