### ISSUE TITLE
Mining waiting time improvement

### ISSUE THREAD

**Issue by jiseongnoh** [klaytn/klaytn#1334]
**Is your request related to a problem? Please describe.**
Current version of Klaytn waits for one second if a block has been mined within a second interval, resulting in potential block generation delay.
For example, if a block was mined at 19.9 seconds, then the worker waits for one second, and starts the mining work at at 20.9 seconds, which is supposed to start at each (20.0) second. 

**Describe the solution you'd like**
I suggest the worker can wait for a fraction of seconds, so the next mining can be started at the scheduled timestamp.

**Describe alternatives you've considered**

**Additional context**

**Comment by aidan-kwon** [comment]
Close this via https://github.com/klaytn/klaytn/pull/1340
