### ISSUE TITLE
How to reduce memory usage?

### ISSUE THREAD

**Issue by islishude** [klaytn/klaytn#1345]
My node takes 30G memory.

**Comment by islishude** [comment]
disk usage is also very high

```
/dev/nvme1n1    4.5T  4.3T  304G  94% /data
```

**Comment by hqjang-pepper** [comment]
There are some ways to reduce memory and disk usage.
- Memory : 30~35% of memory usage of klaytn node is from StateTrie Cache. You can manually reduce this ratio by this command.
` --state.trie-cache-limit [value]`
- Storage : Try using State migration. [Guide link](https://medium.com/klaytn/klaytn-state-migration-an-efficient-way-to-reduce-blockchain-data-6615a3b36523)

**Comment by islishude** [comment]
Thanks, it's very helpful
