### ISSUE TITLE
Is start-block-num option available?

### ISSUE THREAD

**Issue by aad3365** [klaytn/klaytn#1348]
I found an option stated on help command output.
```--start-block-num value                Starts the node from the given block number. Starting from 0 is not supported. (default: 0)```
I gave it a try but it always starts from 0.
If node can starts from specific height, It would be very helpful to optimize data size of server.

**Comment by kjhman21** [comment]
@aad3365 Hi, thanks for making an issue here.
It seems like you want to execute a specific block height with the parameter.
If you want to do that, your node must have a relevant data for the block height. That is, if you want to set it 100, then you actually need to have a data for block height 100. So this can be used to rollback at some block height.

**Comment by aad3365** [comment]
@kjhman21 Thanks for clarification.
I understood what this option can do.
