### ISSUE TITLE
Add klaytn binary version information into Prometheus metric

### ISSUE THREAD

**Issue by odg0318** [klaytn/klaytn#1387]
##  **Is your request related to a problem? Please describe.**
To check the klaytn binary version, I must connect to the instance shell and execute the binary like below.
```shell
$  kcn version
Klaytn v1.8.3
```
I want to check the binary version through Prometheus metrics.

## **Describe the solution you'd like**
I suggest a new metric showing version information by Prometheus label.
```
klaytn_node_version{version="1.8.3"} 1
```

Metric name is `klaytn_node_version` and value is constantly 1.

The version information can be referred in the following code.
https://github.com/klaytn/klaytn/blob/dev/params/version.go#L33

## **Describe alternatives you've considered**
N/A

## **Additional context**
N/A

**Comment by kjhman21** [comment]
@aidan-kwon Could you please look at this?

**Comment by aidan-kwon** [comment]
@odg0318  Thank you for the suggestion. 
Actually, I am sure grafana can show labels of multiple nodes. If you know about this, please give us the link for the documents. 

I think we can achieve the goal with another way. 
How about setting `VersionMajor * 10000 + VersionMinor * 100 + VersionPatch` for the value of the version metric ? 
Or we can make multiple metrics for each VersionMajor, VersionMinor, VersionPatch.

**Comment by odg0318** [comment]
@aidan-kwon Using label in prometheus for version is very common way. I think using label is better way. Let me share some examples from other project. `node_exporter` is very popular project for monitoring node status.

Three metrics are used for version with value `1`.
* go_info
* node_exporter_build_info
* node_os_info

The labels in Prometheus can be shown in Grafana table type.

## example: node_exporter
```
 HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.17.3"} 1

# HELP node_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which node_exporter was built.
# TYPE node_exporter_build_info gauge
node_exporter_build_info{branch="HEAD",goversion="go1.17.3",revision="a2321e7b940ddcff26873612bccdf7cd4c42b6b6",version="1.3.1"} 1

# HELP node_os_info A metric with a constant '1' value labeled by build_id, id, id_like, image_id, image_version, name, pretty_name, variant, variant_id, version, version_codename, version_id.# TYPE node_os_info gauge
node_os_info{build_id="",id="amzn",id_like="centos rhel fedora",image_id="",image_version="",name="Amazon Linux",pretty_name="Amazon Linux 2",variant="",variant_id="",version="2",version_codename="",version_id="2"} 1
```
