### ISSUE TITLE
Hello team. I wanna how to upgrade the klaytn node.

### ISSUE THREAD

**Issue by jam-crypto2021** [klaytn/klaytn#1388]
Hello team. I wanna how to upgrade the klaytn node. may I need to redownload the package and reload the chaindata snapshot?

**Comment by kjhman21** [comment]
Hi @jam-crypto2021 
You just download a new version of binary, and restart the process. That's it. You don't need to download chaindata snapshot if you have already synced data.

If you have more question later, please use [Klaytn Forum](https://forum.klaytn.foundation/) or [Discord](https://discord.io/KlaytnOfficial). You can get answer there more quickly. Thanks.
