### ISSUE TITLE
Dynamic fee test

### ISSUE THREAD

**Issue by kjhman21** [klaytn/klaytn#1410]
**BaseFee** @bobpkr 
Check base fee adjustment according to TPS changes 
- [x] [b-1] check maintaining lower bound of base fee
- [x] [b-2] check maintaining upper bound of base fee
- [x] [b-3] check how many blocks we need to double the base fee
- [x] [b-4] check how many blocks we need to halve the base fee
- [x] [b-5] check base fee you get by BaseFee opcode with contracts
- [x] [b-6] calculate base fee change and compare what applied manually

**Governance** @kjeom 
- [x] [g-1] check default governance parameters for base fee
- [x] [g-2] check if there are side effects when replacing previous binary to hard fork binary
- [x] [g-3] check voting governance parameters for base fee
- [x] [g-4] check an error when voting invalid lower/upper bound base fee
- [x] [g-5] With the governance parameter update, check whether outdated txs are dropped or queued

**TxPool** @kjeom 
- [x] [t-1] an error occurs when sending a tx with a gasPrice lower than the base fee of TxPool
- [x] [t-2] for a sender, all the txs are not promoted (a tx with the lowest nonce has the gasPrice lower than the base fee)
- [x] [t-3] for a sender, the txs with nonce lower than the third tx are only promoted (the third’s has the gasPrice lower than the base fee)
- [x] [t-4] check if the txs with gasPrice lower than the base fee are demoted
- [x] [t-5] check if a tx can replace the old tx with same nonce several times sequentially (cancel transaction also)
- [x] [t-6] txpool performance degrade when base fee is up and down continuously 

**Reward** @kjeom 
- [x] [r-1] check if reward and burning after confirmed a tx with high cost with various reward types (distrubuteReward, mintKlay)
- [x] [r-2] `sum of tx.fee / 2` == `baseFee * gasUsed / 2` @jimni1222 

**Validation** @kjeom 
- [x] [v-1] block.body.tx.gasPrice >= block.header.baseFee

**Hardfork** @yoomee1313 
- [x] [h-1] "fail" check block header encoding/decoding before/after hard fork: call blockByNumber by using klay_client.go
- [x] [h-2] "pass" check tx fee before/after hard fork
- [x] [h-3] "pass" check BaseFee opcode before/after hard fork
- [x] [h-4] "pass"check hardfork ordering
- [x] [h-5] "pass"check hardfork initialization (e.g. init, restart, initial start)
- [x] [h-6] "pass"check hardfork blocknumber re-configure (e.g. 999999999 ->  96733023)
- [x] [h-6] "pass"sync the node start from zero after all test done

**API** @bobpkr @JayChoi1736 
- [x] [a-1] check `GetHeaderByNumber`, `GetHeaderByHash`
- [x] [a-2] check `GetBlockByNumber`, `GetBlockByHash`, `GetBlockWithConsensusInfoByHash`, `GetBlockWithConsensusInfoByNumber`
  - check the existence of the gas price field in dyanmicGasFee tx
- [x] [a-3] check `GetTransactionReceipt` for each transction type
- [x] [a-4] check `GasPriceAt`, `GasPrice` (especially at the governance epoch block) @bobpkr @aidan-kwon 
- [x] [a-5] check `GetTransactionByBlockNumberAndIndex`, `GetTransactionByBlockHashAndIndex`, `GetRawTransactionByBlockHashAndIndex`, `GetTransactionByHash`, `GetRawTransactionByHash`
  - check the existence of the gas price field in dyanmicGasFee tx
- [x] [a-6] check `FeeHistory`
- [x] [a-7] check `MaxPriorityFeePerGas`
- [x] [a-8] check the default values of gas price for `SendTransction`, `SignTransaction`

**Comment by kjhman21** [comment]
test per txtype

**Comment by kjhman21** [comment]
locust test case update

**Comment by kjhman21** [comment]
Since metamask does not allow zero gas price, but there are some cases using gas price as zero for some service chains. Need to test a case that if it works:
lowerbound = 0
tx.gasprice = 1

**Comment by kjeom** [comment]
@kjhman21 It is tested and works well in v1.9.0.
It is maybe failed before v1.9.0 because gasPrice should same with unitPrice in klaytn.

**Comment by aidan-kwon** [comment]
finished
