### ISSUE TITLE
KIP17 토큰이 소각되었을 때 기존 소유자가 Holder로 보이는 현상이 있습니다.

### ISSUE THREAD

**Issue by ChoiYongWook** [klaytn/klaytn#1446]
[https://refs.klaytnapi.com/ko/kip17/v1#operation/MintToken](API 문서)에 나온것처럼 발생을 해서 토큰발행(Token ID : 5)에 성공하였습니다

[Inventory](https://baobab.scope.klaytn.com/nft/0x8f336785ac5cf277fc0311c097c007fe85a97e58?tabId=nftInventory)를 확인했을 때  Holder에 기존에 Token ID가 5의 소유자가 Holder에 노출되어 있고

[[0x7232266e9885211a9889ee754eb50b004f2aff074786425f3869166637cc3231](https://baobab.scope.klaytn.com/tx/0x7232266e9885211a9889ee754eb50b004f2aff074786425f3869166637cc3231?tabId=nftTransfer)](성공한 TxHash)에서는 정상적으로 burn이 되었습니다

[https://baobab.scope.klaytn.com/nft/0x8f336785ac5cf277fc0311c097c007fe85a97e58?tabId=nftHolder](Holder)목록에는 TokenID가 5가 없고 Inventory에서는 노출이 되는데 수정요청드립니다

**Comment by Jongsic** [comment]
안녕하세요. 이곳은 클레이튼 노드와 관련된 Repository 로 스코프에 대한 문의는 Klaytn 공식 Discord 의 개발자-지원 채널에서 저를 찾아주시고 제보해주시면 감사하겠습니다. 

일단 답변 드리자면 해당사항은 패치되었으나 해당 케이스에 대해 과거데이터의 정합성을 전체적으로 맞추는 작업에 약간 시간이 소요될 예정입니다. 새로 토큰 배포하시고 확인해주시면 될 것 같습니다. 감사합니다.

**Comment by aidan-kwon** [comment]
이 이슈는 답변이 된거 같기에 종료하겠습니다.
