### ISSUE TITLE
[SC] Implicit prerequisite of value transfer

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn#1461]
The KLAY, ERC20, and ERC721 tokens are transferrable to the registered counterpart chain via a bridge. However, the sender of value transfer transaction must be aware some of status. For instance, considering the KLAY transfer, the counterpart bridge must hold enough balance than requested KLAY.

KLAY:        The receiver bridge must have enough balance at the time of value transfer request.
ERC20:     No further design or change is required if burning & minting mechanism is applied
ERC721:   The token ID must not be owned at the time of value transfer. Redesigned via #1460

**Comment by hyunsooda** [comment]
Ongoing at #1595

**Comment by sjnam** [comment]
closed #1565
