### ISSUE TITLE
Tests for v1.9.0

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1463]
Target Release date: 7/28
- [x] https://github.com/klaytn/klaytn/issues/1474
- [x] https://github.com/klaytn/klaytn/issues/1410 
- [x] https://github.com/klaytn/klaytn/issues/1463#issuecomment-1170676781 @hyunsooda 
- [x] https://github.com/klaytn/klaytn/issues/1463#issuecomment-1170751924 @hqjang-pepper 
- [x] https://github.com/klaytn/klaytn/issues/1463#issuecomment-1174634349 @blukat29 
- [x] https://github.com/klaytn/klaytn/issues/1463#issuecomment-1177329097 @mckim19 
- [x] https://github.com/klaytn/klaytn/issues/1463#issuecomment-1179838720 @yoomee1313 
- [x] [Regular Test](https://github.com/klaytn/klaytn/issues/1463#issuecomment-1180112077) @JayChoi1736 
- [x] https://github.com/klaytn/klaytn/issues/1536 @ian0371 
- [x] [Additional Test with rc.3](https://github.com/klaytn/klaytn/issues/1463#issuecomment-1190962490)

**Comment by bobpkr** [comment]
- #1410

**Comment by hyunsooda** [comment]
- #1427

**Comment by hqjang-pepper** [comment]
https://github.com/klaytn/klaytn/pull/1371
https://github.com/klaytn/klaytn/pull/1408

**Comment by blukat29** [comment]
- [ ] https://github.com/klaytn/klaytn/pull/1464
  - [ ] `governance_getStakingInfo` returns nonnegative Gini with "latest" block
  - [ ] `governance_getStakingInfo` returns nonnegative Gini with any past blocks

**Comment by mckim19** [comment]
- [ ] https://github.com/klaytn/klaytn/pull/1468
  - [ ] check the return value of RPC call

- [ ] https://github.com/klaytn/klaytn/pull/1462
  - [ ] check the number of consensus messages

**Comment by yoomee1313** [comment]
- [ ] https://github.com/klaytn/klaytn/pull/1470
  - [ ] tc1. call api functions which calls Snapshot() function - target block: voteData block, governanceData block
  - [ ] tc2. restart the node when voting, then call api functions which calls Snapshot() function
- [ ] https://github.com/klaytn/klaytn/pull/1389
  - [ ] tc1. disconnect the connection between multichannel peer and see the connection is disconnected and reconnect.
  - [ ] tc2. restart the other node of the connection( not the testing node) and see the connection is disconnected and reconnect.

**Comment by JayChoi1736** [comment]
**Regular QA Test**
- [ ] Rolling Update test: 
- [ ] RPC/WS test: 
- [ ] Governance test: 
- [ ] Reward test: 
- [ ] Caver js/java test: 
- [ ] Sync test 
  - Node Configuration
    - en0(c5.4xlarge, 6T): sync from 0 to latest
    - en1(c5.4xlarge, 6T): sync from 52007590 to 76539733
    - en2(c5.4xlarge, 6T): sync from 76539733 to 85394216
    - en3(c5.4xlarge, 6T): sync from 85394216 to latest

- [ ] Load test 
  - [ ] Stress: 10000 RPS load test for 30m
    - TC: valueTransferTC
    - TPS: 
  - [ ] Reliability: 2000 RPS load test for 72h 
    - TC: transferSignedTx, newValueTransferTC, newFeeDelegatedSmartContractExecutionTC
    - TPS: 

- [ ] API performance test:

**Comment by aidan-kwon** [comment]
**Additional Test with rc.3**

- [ ]

**Comment by hyunsooda** [comment]
An item `Value transfer between chains is possible when the base fee is changing` is duplicated test with the tests performed. Could you precisely elaborate on which test should be additionally performed? cc. @2dvorak

**Comment by aidan-kwon** [comment]
> @aidan-kwon, An item `Value transfer between chains is possible when the base fee is changing` is duplicated test with the tests performed. Could you precisely elaborate on which test should be additionally performed? cc. @2dvorak

@hyunsooda  During QA process, we have merged influential PRs that can affect key operations of Klaytn. So, we try to execute some tests again to ensure the correct operation related to the change.

**Comment by hyunsooda** [comment]
@aidan-kwon, Okay, thanks.

**Comment by JayChoi1736** [comment]
[stress_rc3](https://user-images.githubusercontent.com/102955810/180693527-f1a03a99-d2aa-4264-b5d3-4c6f6c79f237.png)

v1.9.0-rc.3
10000 RPS stress test for 30m
TC: transferSignedTx
TPS: 6300
CN : c6.x8large

**Comment by blukat29** [comment]
Base Fee test OK

Version: v1.9.0-rc.3
For each block, send a contract executing transaction with varying gasLimit
Calculated desired BaseFee using Excel and compared against actual BaseFee in the blockchain.
[BaseFee test v1.9.0-rc.3 20220725.xlsx](https://github.com/klaytn/klaytn/files/9180275/BaseFee.test.v1.9.0-rc.3.20220725.xlsx)

**Comment by yoomee1313** [comment]
Invalid block body having an invalid gas price test passed.

en receives the block which having invalid gas price tx(24999999998), and it returns bad block with invalid baseFee error.

```
ERROR[07/26,09:37:44 +09] [5] ########## BAD BLOCK ######### Chain config: {ChainID: 940625 IstanbulCompatibleBlock: 0 LondonCompatibleBlock: 0 EthTxTypeCompatibleBlock: 0 MagmaCompatibleBlock: 5 SubGroupSize: 4 UnitPrice: 25000000000 DeriveShaImpl: 2 Engine: istanbul} Number: 5 Hash: 0x9ed658b1179560316bd0f3148c5c6a9afaaa73d2e7a358c000d43fe957872017 Receipt:  Error: invalid baseFee: have 24999999998, want 25000000000, parentBaseFee <nil>, parentGasUsed 0 
```

**Comment by 2dvorak** [comment]
Value transfer between chains was successful with below conditions (all binaries v1.9.0-rc.3).
- Parent (before Magma) <-> Child (before Magma)
- Parent (after Magma) <-> Child (before Magma)
- Parent (before Magma) <-> Child (after Magma)
- Parent (after Magma) <-> Child (after Magma)

**Comment by aidan-kwon** [comment]
All tests have passed
