### ISSUE TITLE
Snapshot synchronization test

### ISSUE THREAD

**Issue by jeongkyun-oh** [klaytn/klaytn#1474]
Test snapshot synchronization

## Related changes
- https://github.com/klaytn/klaytn/pull/1394
- https://github.com/klaytn/klaytn/pull/1395
- https://github.com/klaytn/klaytn/pull/1434
- https://github.com/klaytn/klaytn/pull/1435
- https://github.com/klaytn/klaytn/pull/1441
- https://github.com/klaytn/klaytn/pull/1443
- https://github.com/klaytn/klaytn/pull/1450
- https://github.com/klaytn/klaytn/pull/1451
- https://github.com/klaytn/klaytn/pull/1454
- https://github.com/klaytn/klaytn/pull/1455
- https://github.com/klaytn/klaytn/pull/1456
- https://github.com/klaytn/klaytn/pull/1457
- https://github.com/klaytn/klaytn/pull/1469
- https://github.com/klaytn/klaytn/pull/1473
- https://github.com/klaytn/klaytn/pull/1500

## Unittest
> check and make more unit tests about snapshot synchronization change
- [x] 1394. protocol test (incl. multichannel) - istanbul65 (65-65, 65-64 connections)
- [x] 1394. send/receive invalid staking information (or null)
- [x] 1441. state sync node expansion ordering test
- [x] 1450. protocol test - istanbul65 (non-istanbul engine, non-weighted random policy)
- [x] 1469. trie sync based on path (ethereum)
- [x] 1473. snapsync downloader test - snap/1
- [x] 1473. flags test - full, snap only available
- [x] 1473. downloader snap packets test
- ~1395. `spindownStateSync` unittest (ethereum)~
- ~1441. state sync node expansion max depth test (ethereum)~
- ~1469. trieGetNode unittest (ethereum)~
- ~1454. dynamic pivot movement test (ethereum)~

## Consistency/Sync Test
> check database consistency after synchronization
- [x] snap sync test
  - [x] baobab sync with nodes having snapshot data
  - [x] cypress sync with nodes having snapshot data
  - [x] baobab sync with multi version of node (binary version, snapshot feature turning on/off, archive/full, ...)
  - [x] cypress sync with multi version of node (binary version, snapshot feature turning on/off, archive/full, ...)
    - **_issue: too long heal phase_**
- [x] implement test subcommand to test following things - @ethan-kr 
  - [x] add a subcommand to veirfy snapshot data by creating a trie with snapshot and compare the root hash
  - [x] add a subcommand to verify a trie from root to leaf
    - ~option1. compare the created trie with the stored trie~
    - [x] option2. iterate trie from root and check if a node is missing or not
- [x] verify data consistency right after snapsync - @ethan-kr 
  - [x] baobab snapshot data consistency
  - [x] cypress snapshot data consistency
  - [x] baobab state(+storage) trie data consistency
  - [x] cypress state(+storage) trie data consistency

## Dependency test
> check and test if these changes have side effects to other parts of codes
Test env. How to? What makes side effects?  turn on/off nodes, ... 
- [x] protocol compatibility test - istanbul65
  - [x] test node connections (64-65, 64-64, 65-65, snapshot on/off)
    - **_issue: `["istanbul/64", "istanbul/65", "snap/1", "snap/1"]`_**
- [x] state db migration (+ node turning on/off)
  - [x] baobab db migration working
  - [x] cypress db migration working
  - [x] baobab state trie data consistency
  - [x] cypress state trie data consistency
- [ ] full synchronisation - extract metrics to compare snapsync
- [x] contract code prefix (unittest?)
  - ~sync with old version and update it to new binary~

**Comment by ethan-kr** [comment]
Check whether snapshot sync works well in issue situations
  - Kakao Pay traffic situation
  - 2022 1Q traffic situation
 - Block generation stopped at the end of 2021
Verify data validation
  - Situation in which some data is deleted or missing during sync: Assuming there is a bug
  - A situation in which some nodes are restarted periodically
A situation where various nodes are mixed
  - Nodes with protocol version 64 and lower
  - Nodes with snapshot disabled
etc. Can I proceed with snapshot sync with the snapshot function turned off?
