### ISSUE TITLE
Figure out badgerDB test failure

### ISSUE THREAD

**Issue by hqjang-pepper** [klaytn/klaytn#1486]
I found some test failure condition at database package.
BadgerDB fails to open a new database if we try to write some data in our testcode.
But it doesn't return any failure log. So we have to figure it out.

Related PR : 
- https://github.com/klaytn/klaytn/pull/1371

**Comment by aidan-kwon** [comment]
Closed since it is minor and temporary resolved in #1371 
https://github.com/klaytn/klaytn/pull/1371#discussion_r913111862
