### ISSUE TITLE
Decreased tx propagation capability after v1.8.3(related to process transactions first come, first served)

### ISSUE THREAD

**Issue by mckim19** [klaytn/klaytn#1525]
**Describe the bug**
This is not about the bug but klaytn developers should know this situation i think.
[I.8.3 tag](https://github.com/klaytn/klaytn/releases/tag/v1.8.3) includes to change processing transactions.
It seems to require more computing power for ordering txs.
So, TPS was lower than previous version of 1.8.3. when I tested the performance of klaytn network that i configured.
Before 1.8.3 update, Klaytn network was stable for 4000 TPS even if a few nodes received all the load.
After updating to 1.8.3, The maximum tps was 2500 in a specific situation where a small number of nodes received all the load.
The test result was attached.

**How to reproduce**
If use the klaytn-deploy tool, configuring the klaytn network is easier.
The conf.json that contain the detail of network configuration will be attached. 

1. Create Klaytn network with locust master and slave : CN4:PN8 (CN full mesh, PN ring) 
2. Create about eight ENs and connect all of ENs to only two PN(one CC: one CN+two PNs).
3. Request txs to ENs using the locust.

CN 4, PN 8, EN 8, Locust master 1, Locust slave 4, grafana 1
RPS: 5,000
Users: 500
Hatch Rate: 100
NumAccForSignedTx: 100,000
ActiveAccPercent: 100
SlavesPerNode:5
 
 
**Expected behavior**
If Klaytn version is over 1.8.3, the maximum tps is under 2500. 

**Attachments**

v1.8.0=> 4000tps
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/59811055/178980220-e281f81f-21ac-456e-bf81-ad1524eae766.png">

v1.8.2=> 4000tps
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/59811055/178980068-12bea928-3ac8-4315-846a-c2a8a4dfc562.png">

v1.8.3=> 2000~2500tps
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/59811055/178980132-340a414f-43d0-41ff-9341-ca4a97651a2c.png">

v1.8.4=> 2000~2500tps
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/59811055/178980018-d8f9e5a8-5eb7-463a-ad03-bb5b8651e679.png">

Configuration File
[conf.json.txt](https://github.com/klaytn/klaytn/files/9111771/conf.json.txt)

**Environment**
 - After Klaytn v1.8.3
 - go version go1.18.3 darwin/arm64
 - macOS/12.4

**Comment by aidan-kwon** [comment]
The block generation capability does not decrease much, but the block propagation capability from a single node decreased.  So, the TPS can be recoverable when a network has more PN/EN like Cypress.

Increasing TPS is an ordinary development goal and this issue itself is hard to find a specific solution for the issue since the performance decrement was expected at that time. And, [the recent experiment](https://github.com/klaytn/klaytn/issues/1676#issuecomment-1314623575) shows better performance than this. So, close this issue.
