### ISSUE TITLE
Cannot run `go get` when using go module

### ISSUE THREAD

**Issue by frostornge** [klaytn/klaytn#153]
**Describe the bug**
I'm using go module.
`go get` keeps failing with this error message `cannot load gopkg.in/urfave/cli.v1: cannot find module providing package gopkg.in/urfave/cli.v1`.

**How to reproduce**
1. make new go mod project.
2. run `GO111MODULE=on go get github.com/klaytn/klaytn`
3. make main.go with this code
``` golang
_, _ = client.Dial("")
```
4. go run main.go

**Expected behavior**
Clearly working `go get` command

**Attachments**
```
❯ go run main.go
go: downloading gopkg.in/urfave/cli.v1 v1.21.0
build command-line-arguments: cannot load gopkg.in/urfave/cli.v1: cannot find module providing package gopkg.in/urfave/cli.v1
```

**Environment**
 - Klaytn version: `v1.0.0`
 - Go version: `1.12.7`
 - OS and its version: `macOS/10.14.3`

**Additional context**
related #84

**Comment by frostornge** [comment]
I added `gopkg.in/urfave/cli.v1 v1.20.0 // indirect` in `go.mod` manually, and got
```
❯ go run main.go
# github.com/klaytn/klaytn/networks/rpc
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/networks/rpc/server.go:57:3: cannot use set.New() (type set.Interface) as type *set.Set in field value: need type assertion
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/networks/rpc/server.go:57:20: not enough arguments in call to set.New
        have ()
        want (set.SetType)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/networks/rpc/websocket.go:145:20: not enough arguments in call to set.New
        have ()
        want (set.SetType)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/networks/rpc/websocket.go:183:20: not enough arguments in call to set.New
        have ()
        want (set.SetType)
# github.com/klaytn/klaytn/accounts/keystore
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/accounts/keystore/account_cache.go:87:26: undefined: set.NewNonTS
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/accounts/keystore/file_cache.go:56:9: undefined: set.NewNonTS
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/accounts/keystore/file_cache.go:57:10: undefined: set.NewNonTS
# github.com/klaytn/klaytn/storage/database
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/storage/database/badger_database.go:42:6: opts.Dir undefined (type func(string) badger.Options has no field or method Dir)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/storage/database/badger_database.go:43:6: opts.ValueDir undefined (type func(string) badger.Options has no field or method ValueDir)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/storage/database/badger_database.go:45:2: cannot use opts (type func(string) badger.Options) as type badger.Options in return argument
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/storage/database/badger_database.go:126:19: too many arguments in call to txn.Commit
        have (nil)
        want ()
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/storage/database/badger_database.go:137:13: assignment mismatch: 2 variables but item.Value returns 1 values
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/storage/database/badger_database.go:137:26: not enough arguments in call to item.Value
        have ()
        want (func([]byte) error)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/storage/database/badger_database.go:149:2: not enough arguments to return
        have (error)
        want ([]byte, error)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/storage/database/badger_database.go:149:19: not enough arguments in call to item.Value
        have ()
        want (func([]byte) error)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/storage/database/badger_database.go:160:19: too many arguments in call to txn.Commit
        have (nil)
        want ()
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/storage/database/badger_database.go:204:21: too many arguments in call to b.txn.Commit
        have (nil)
        want ()
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.0.0/storage/database/badger_database.go:204:21: too many errors
```

**Comment by frostornge** [comment]
aws/aws-lambda-go#222 this solution works well, but got same errors..

**Comment by kjhman21** [comment]
Thanks for the report.

@ehnuje Could you look into this, please?

**Comment by ehnuje** [comment]
@frostornge @kjhman21 I've reproduced the issue on my local. I will further investigate the issue and update here.

**Comment by frostornge** [comment]
urfave/cli#859 This issue suggests that use `github.com` rather than `gopkg.in`.
When using `go module`, just add this code in `go.mod`.
`replace gopkg.in/urfave/cli.v1 => github.com/urfave/cli v1.21.0`.

**Comment by NEO2756** [comment]
**Getting the same issue:** 
**sandeeps-MBP:launcher-docker neo$ go version
go version go1.12.6 darwin/amd64**

sandeeps-MBP:launcher-docker neo$ go build 
# github.com/klaytn/klaytn/networks/rpc
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/networks/rpc/server.go:57:3: cannot use set.New() (type set.Interface) as type *set.Set in field value: need type assertion
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/networks/rpc/server.go:57:20: not enough arguments in call to set.New
	have ()
	want (set.SetType)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/networks/rpc/websocket.go:145:20: not enough arguments in call to set.New
	have ()
	want (set.SetType)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/networks/rpc/websocket.go:183:20: not enough arguments in call to set.New
	have ()
	want (set.SetType)
# github.com/klaytn/klaytn/storage/database
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:42:6: opts.Dir undefined (type func(string) badger.Options has no field or method Dir)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:43:6: opts.ValueDir undefined (type func(string) badger.Options has no field or method ValueDir)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:45:2: cannot use opts (type func(string) badger.Options) as type badger.Options in return argument
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:126:19: too many arguments in call to txn.Commit
	have (nil)
	want ()
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:137:13: assignment mismatch: 2 variables but item.Value returns 1 values
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:137:26: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:149:2: not enough arguments to return
	have (error)
	want ([]byte, error)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:149:19: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:160:19: too many arguments in call to txn.Commit
	have (nil)
	want ()
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:204:21: too many arguments in call to b.txn.Commit
	have (nil)
	want ()
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/storage/database/badger_database.go:204:21: too many errors
# github.com/klaytn/klaytn/accounts/keystore
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/accounts/keystore/account_cache.go:87:26: undefined: set.NewNonTS
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/accounts/keystore/file_cache.go:56:9: undefined: set.NewNonTS
../../../go/pkg/mod/github.com/klaytn/klaytn@v1.1.1/accounts/keystore/file_cache.go:57:10: undefined: set.NewNonTS
