### ISSUE TITLE
Tests for v1.9.0 - Ethereum tools convenience

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1536]
Check whether there is any convenience using the following tools after Magma hard-fork.
It should resolve inconveniences that come from the fixed gas price policy. 
Reference: https://github.com/klaytn/klaytn/issues/1192

- [x] MetaMask
- [x] web3.js
- [x] ethers.js
- [x] truffle
- [x] hardhat
- [x] homestead signer for CREATE2 Factory (related PR: https://github.com/klaytn/klaytn/pull/1539)

**Comment by ian0371** [comment]
## web3.js
transaction related function | web3.js | ok
-- | -- | --
eth_signTransaction | web3.eth.signTransaction | O
eth_sendRawTransaction | web3.eth.sendSignedTransaction | O
eth_sendTransaction | web3.eth.sendTransaction | N/A
eth_call | contract.methods.myMethod().call | O

- `eth_sendTransaction` requires the node to have the private key for signing txs.
- `eth_signTransaction` requires tx object to specify gas, which is consistent with Ethereum.
- `signTransaction` and `sendSignedTransaction` includes value transfer, smart contract deploy & execution.
- web3.js invokes `eth_call` with an empty `from` address field

## ethers.js
transaction related function | ethers.js | ok
-- | -- | --
eth_signTransaction | web3.eth.signTransaction | N/A
eth_sendRawTransaction | ethers.ContractFactory.send | O
eth_sendTransaction | signer.sendTransaction | N/A
eth_call | ethers.ContractFactory.myMethod() | O

- `eth_estimateGas` is internally called before sending tx
- ethers.js invokes `eth_call` with `from` address field filled with the wallet's address

**Comment by ian0371** [comment]
## truffle
version: v5.5.22

truffle sample MetaCoin test: ALL PASS, which includes:
- migration test (contract deploy)
- unit test (contract send & call)

## hardhat
hardhat version: 2.10.1

hardhat sample Greeter test: ALL PASS, which includes:
- contract deploy
- unit test (contract send & call)

## Homestead signer
ALL PASS for the steps in https://github.com/ProjectOpenSea/seaport/blob/main/docs/Deployment.md

## Notes
- All the aforementioned have been also tested under the base-fee changing situation
- Refer https://github.com/ian0371/klay-eth-equiv-test to the instructions

**Comment by aidan-kwon** [comment]
finished
