### ISSUE TITLE
Read-Only EN

### ISSUE THREAD

**Issue by hqjang-pepper** [klaytn/klaytn#1547]
Certainly there are some needs to operate EN which can do read operation only.
(Sendtransaction is impossible with this EN)
For example, purpose of operation EN is only fetching chaindata, or some ServiceChain EN operators who don't want public users send transactions through their nodes.
Can we make flag option that does not allow sending transaction to ksen service?

**Comment by aidan-kwon** [comment]
Let's consider this when the requirements are more concrete.
