### ISSUE TITLE
Voted using governance in single node scn, however does not update changes

### ISSUE THREAD

**Issue by brew0722** [klaytn/klaytn#1556]
## test Environment
`kscn version`: Klaytn v1.8.4+70a8cb6dcd
I was launched a local service chain with single scn node for test the governance vote.
And for quick test, genesis.json modified `istanbul.epoch` field to 60.

### 1. tried to change the `governanceMode` from `none` to `single`.

a. enter the vote command
```
governance.vote("governance.governancemode","single")
"Your vote was successfully placed."
```

b. check the vote submission 
Subsequently, check `myVotes` field of governance, it appears that it was submitted successfully as `Casted: true`. And it was added to the `pending changes`.

```
> governance
{
  chainConfig: {
    chainId: 1000,
    deriveShaImpl: 2,
    ethTxTypeCompatibleBlock: 0,
    governance: {
      governanceMode: "none",
      governingNode: "0x0000000000000000000000000000000000000000",
...
    },
    istanbul: {
      epoch: 60,
      policy: 0,
      sub: 22
    },
    istanbulCompatibleBlock: 0,
    londonCompatibleBlock: 0,
    unitPrice: 0
  },
  idxCache: [0, 60],
  idxCacheFromDb: [0, 60],
  myVotes: [{
      BlockNum: 106,
      Casted: true,
      Key: "governance.governancemode",
      Value: "single"
  }],
  myVotingPower: undefined,
  nodeAddress: "0x1576d0d4c7d402ff567a8b79e7683dd0bf2cb4a1",
  pendingChanges: {
    governance.governancemode: "single"
  },
  showTally: [{
      ApprovalPercentage: 100,
      Key: "governance.governancemode",
      Value: "single"
  }],
  totalVotingPower: undefined,
  votes: [{
      key: "governance.governancemode",
      validator: "0x1576d0d4c7d402ff567a8b79e7683dd0bf2cb4a1",
      value: "single"
  }],
```

c. Wait for epoch and check for change updates

```
> klay.blockNumber
1510
> governance
{
  chainConfig: {
    chainId: 1000,
    deriveShaImpl: 2,
    ethTxTypeCompatibleBlock: 0,
    governance: {
      governanceMode: "none",
      governingNode: "0x0000000000000000000000000000000000000000",
...
    },
    istanbul: {
      epoch: 60,
      policy: 0,
      sub: 22
    },
    istanbulCompatibleBlock: 0,
    londonCompatibleBlock: 0,
    unitPrice: 0
  },
...
}
```

The results don't seem to have changed.
However, subsequent attempts at other votes fail with PermissionDenied.
```
> governance.vote("istanbul.epoch", 30)
Error: You don't have the right to vote
    at web3.js:3278:20
    at web3.js:6805:15
    at web3.js:5216:36
    at <anonymous>:1:1
```

### Questions
1. Is there any mistake in the test I tried?
2. If the governance mode is none, is it correct that if any member of the council submit a vote then it will be applied in the next epoch regardless of the number of votes cast (`ApprovalPercentage`)?
3. Is there no exception if the `GoverningNode` remains as the `DefaultGoverningNode` and changes to the single mode?
Does the chain no longer have the author to vote?

**Comment by blukat29** [comment]
1. The effects of governance vote are reflected in `governance.itemsAt()` API. `governance.chainConfig` shows the initial state.
2. Yes. Under `none` mode, one vote from any council member can change settings.
3. Yes. No one can vote if the chain state is in `single` mode with governing node `0x0` ([code](https://github.com/klaytn/klaytn/blob/v1.8.4/governance/handler.go#L423)). Unfortunately, there is no fallback for such cases.

**Comment by brew0722** [comment]
thks! I understood it well with your hlep. I hope that the exception for case 3 can be prevented in the next scheduled governance feature update.
