### ISSUE TITLE
Disconnection between CNs during heavy load.

### ISSUE THREAD

**Issue by mckim19** [klaytn/klaytn#1557]
**Describe the bug**
It seems that there were disconnections between CNs during heavy load.

**How to reproduce**
step1. Create Klaytn network with locust master and slave : CN5:PN10:EN10 (CN full mesh, PN ring)
step2. connect one EN to two PN. 
step3. Request about 5000 txs to ENs using the locust.

**Expected behavior**
For the test, there were a lot of transactions in the network, the connection between CNs was disconnected. 
<img width="1459" alt="image" src="https://user-images.githubusercontent.com/59811055/181424000-982bfdaf-b898-413c-9e36-1ed6a749b121.png">

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/59811055/181423713-20c4ad49-eaf7-47fe-b280-3f45be5e19e2.png">
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/59811055/181423774-05c5722c-ef40-44d6-859b-f7e3bf31ece1.png">
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/59811055/181423814-2a310a25-8feb-42f1-a0d5-703c8773a5cb.png">
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/59811055/181423885-0aa4c073-1339-4d0a-998f-d7cf0a906f25.png">

**Attachments**
[cn1.log](https://github.com/klaytn/klaytn/files/9197932/cn1.log)
[cn2.log](https://github.com/klaytn/klaytn/files/9197931/cn2.log)

**Environment (please complete the following information)**
- Klaytn v1.8.4
- go version go1.18.3 darwin/arm64
- macOS/12.4

**Comment by yoomee1313** [comment]
This is similar to #1358. Close the issue.
