### ISSUE TITLE
Integrate rosetta testing into QA phase

### ISSUE THREAD

**Issue by kjhman21** [klaytn/klaytn#1568]
After making a testing guide manual by @jimni1222, please include this in our QA phase.
It was good to check data consistency.

**Comment by jimni1222** [comment]
I wrote down [how to perform rosetta-klaytn's check:data test](https://github.com/klaytn/rosetta-klaytn/wiki/How-to-run-check:data-testing-for-data-consistency).

However, rosetta-klaytn v1.0.1 must be released to work according to this guide, so after v1.0.1 version is released, i will put additional comment in here.

**Comment by jimni1222** [comment]
@aidan-kwon I checked the [testing guide](https://github.com/klaytn/rosetta-klaytn/wiki/How-to-run-check:data-testing-for-data-consistency) with rosetta-klaytn v1.0.1 (latest version).

cc @kjhman21

**Comment by blukat29** [comment]
Rosetta testing is now part of our regular QA. cf. https://github.com/klaytn/klaytn/issues/2043
