### ISSUE TITLE
Cannot initialize KIP71 params of Governance in Genesis

### ISSUE THREAD

**Issue by brew0722** [klaytn/klaytn#1577]
**Describe the bug**
I understood that if KIP71's `lowerboundBaseFee` is modified in the service chain, the baseFee will be lowered and Tx can be sent without a fee.
I wrote governance in Genesis of the new service chain. but the entered KIP71 was not applied.
And I found the code that apply Genesis governance with the config below, but I couldn't find the content that reflects KIP71.
https://github.com/klaytn/klaytn/blob/1e159b971fcc52616b44bf102110bd5b83b9a995/governance/default.go#L1072

Can't I enter the initial value of KIP71 in Genesis?

**How to reproduce**
1. modify genesis.json with kip71 of governance.
2. init single node with modified genesis.json. (Initialize new chain, not upgrade)
3. kscn start and query `governance.itemsAt("latest")`
4. The entered value is not applied and is displayed as default value. 

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.
Below is the governance that I tried to initialize.
```
        "governance": {
            "governanceMode": "none",
            "governingNode": "0x1000000000000000000000000000000000000000", //<--This is a value for test whether the value I entered is applied well.
            "kip71": {
                "lowerboundbasefee": 0,
                "upperboundbasefee": 750000000000,
                "gastarget": 30000000,
                "maxblockgasusedforbasefee": 60000000,
                "basefeedenominator": 20
            },
            "reward": {
                "mintingAmount": 9600000000000000000,
                "ratio": "100/0/0",
                "useGiniCoeff": false,
                "deferredTxFee": false,
                "stakingUpdateInterval": 86400,
                "proposerUpdateInterval": 3600,
                "minimumStake": 2000000
            }
```

And the kip71 not applied after chain initialization.
```
> governance.itemsAt("latest")
{
  governance.governancemode: "none",
  governance.governingnode: "0x1000000000000000000000000000000000000000",
  governance.unitprice: 0,
  istanbul.committeesize: 22,
  istanbul.epoch: 10,
  istanbul.policy: 0,
  kip71.basefeedenominator: 20,
  kip71.gastarget: 30000000,
  kip71.lowerboundbasefee: 25000000000,
  kip71.maxblockgasusedforbasefee: 60000000,
  kip71.upperboundbasefee: 750000000000,
  reward.deferredtxfee: false,
  reward.minimumstake: "2000000",
  reward.mintingamount: "9600000000000000000",
  reward.proposerupdateinterval: 3600,
  reward.ratio: "100/0/0",
  reward.stakingupdateinterval: 86400,
  reward.useginicoeff: false
```

**Environment (please complete the following information)**
 -Klaytn v1.9.0+51c0105b62
 
**Additional context**

**Comment by kjeom** [comment]
You can update the values by governance vote.
Voting is only supported to change the values. 
The KIP-71 init feature by genesis can be supported after refactoring the governance.

Thanks.
