### ISSUE TITLE
kip71 parameters are not updated

### ISSUE THREAD

**Issue by egonspace** [klaytn/klaytn#1578]
**Describe the bug**
I'm running 4 node-service chain with klaytn v1.9.0 and I configured kip71 parameters as follows.
```
governance.vote("kip71.lowerboundbasefee", 0)
governance.vote("kip71.upperboundbasefee", 0)
```

After two epoch, I found that the parameters are updated to 0 successfully from 3 nodes, but
for one scn node, the parameters are not updated.

```
node 2~4:
kip71: {
        basefeedenominator: 20,
        gastarget: 30000000,
        lowerboundbasefee: 0,
        maxblockgasusedforbasefee: 60000000,
        upperboundbasefee: 0
      },

node 1:
kip71: {
        basefeedenominator: 20,
        gastarget: 30000000,
        lowerboundbasefee: 25000000000,
        maxblockgasusedforbasefee: 60000000,
        upperboundbasefee: 750000000000
      },
```

Aren't these parameters common on all chain nodes? How can it come out differently?

**How to reproduce**

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - Klaytn version or git revision that exhibits the issue `$ ken version`
 - go version `$ go version`
 - OS and its version [e.g. macOS/10.14]

**Additional context**

**Comment by 2dvorak** [comment]
Is the block number of the problematic node same as others?

Also, can you reproduce the behavior? As you said, `governance.vote` should update all nodes in the network, and when I tested locally, the above issue isn't reproduced.

**Comment by egonspace** [comment]
> Is the block number of the problematic node same as others?

Yes, it is. block is syncing.

> Also, can you reproduce the behavior? As you said, governance.vote should update all nodes in the network, and when I tested locally, the above issue isn't reproduced.

Well, I don't think I did any special actions. Only tasks such as attempting a voting on the first node, but attempting a voting again before epoch, restarting the node in that state, etc.

**Comment by egonspace** [comment]
This just seems to be a problem that the values of the governance field are not synchronized with the actual value.
```
> governance
{
  chainConfig: {
    chainId: 20221,
    deriveShaImpl: 2,
    ethTxTypeCompatibleBlock: 0,
    governance: {
      governanceMode: "none",
      governingNode: "0x0000000000000000000000000000000000000000",
      kip71: {
        basefeedenominator: 20,
        gastarget: 30000000,
        lowerboundbasefee: 25000000000,
        maxblockgasusedforbasefee: 60000000,
        upperboundbasefee: 750000000000
      },
      reward: {
        deferredTxFee: false,
        minimumStake: 2000000,
        mintingAmount: 0,
        proposerUpdateInterval: 3600,
        ratio: "100/0/0",
        stakingUpdateInterval: 86400,
        useGiniCoeff: false
      }
    },
    istanbul: {
      epoch: 3600,
      policy: 0,
      sub: 22
    },
    istanbulCompatibleBlock: 0,
    londonCompatibleBlock: 0,
    magmaCompatibleBlock: 0,
    unitPrice: 0
  },
  idxCache: [0, 72000, 75600, 79200, 82800],
  idxCacheFromDb: [0, 72000, 75600, 79200, 82800],
  myVotes: [],
  myVotingPower: undefined,
  nodeAddress: "0x6e14f8bf5a3c70b9a5b9c2d451fc5fb7de292ce2",
  pendingChanges: {},
  showTally: [],
  totalVotingPower: undefined,
  votes: [],
  getChainConfig: function(callback),
  getIdxCache: function(callback),
  getIdxCacheFromDb: function(callback),
  getMyVotes: function(callback),
  getMyVotingPower: function(callback),
  getNodeAddress: function(callback),
  getPendingChanges: function(callback),
  getShowTally: function(callback),
  getStakingInfo: function(),
  getTotalVotingPower: function(callback),
  getVotes: function(callback),
  itemCacheFromDb: function(),
  itemsAt: function(),
  vote: function()
}
> klay.lowerBoundGasPrice
0

```

**Comment by kjeom** [comment]
@egonspace The chainConfig is for genesis configuration. But we have temporarily added KIP-71 parameters in it.
You should get the actual value by calling the API
ex) klay.getHeader for baseFeePerGas, klay.lowerBoundGasPrice for lowerboundGasPrice...
And the changed parameters you can get by calling governance.itemsAt(epoch*2 block number after voted).
