### ISSUE TITLE
Homi output improvement for reward

### ISSUE THREAD

**Issue by odg0318** [klaytn/klaytn#1602]
**Is your request related to a problem? Please describe.**
Homi can generate node data such as node key, address, password, genesis.json and reward address. Among them, reward data cannot be easily parsed because the data is stored in anonymous file. Loot at the following output.

### homi output
```shell
homi-output/
  keys/
     nodekey1 
     nodekey2
     passwd1
     passwd2
     UTC--2022-08-19T00-17-15.485928000Z--46879cdc21832d6bd6b49081513fa3d965443075  # <--- reward data is stored here
     UTC--2022-08-19T00-17-16.930261000Z--447e14fe387d9b62ee1e383158c90fb1257631e6  # <--- reward data is stored here
     validator1
     validator2
  keys_test/
  scripts/
    genesis.json
    static-nodes.json
  Klaytn.json
  Klaytn_txpool.json
```

In the above, nodekey, passwd and validator are store in a file having a specific name but reward data is store in a file having prefix `UTC-YYYY-MM-dd-XXXXXXXX--YYYYYY`. Therefore, we cannot specify a file having reward data with the files.

**Describe the solution you'd like**
I suggest to generate `rewardN` file (for example, reward1, reward2) instead of UTC-XXX including reward key, reward address.

### reward1
```json
{
      "Address": "0x46879cdc21832d6bd6b49081513fa3d965443075",
      "Key": "d647473a06916365ea3bbe2e0940ae81f693e2f953df66919ffb2630c82f0632"
}
```

And then `UTC-XXX` file looks like keystore file so that the files must be renamed to `keystoreN`.

Finally, one node has the following outputs.
* nodekey1
* passwd1
* validator1
* reward1
* keystore1

And so the output layout I suggest is like the below.
```
homi-output/
  keys/
     keystore1
     keystore2
     nodekey1
     nodekey2
     passwd1
     passwd2
     reward1
     reward2
     validator1
     validator2
  keys_test/
  scripts/
    genesis.json
    static-nodes.json
  Klaytn.json
  Klaytn_txpool.json
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hqjang-pepper** [comment]
I'll handle this.

**Comment by odg0318** [comment]
@hqjang-pepper As I deeply look into the codes, I found this line to generate UTC-XXX files which is a kind of keystore file.

* https://github.com/klaytn/klaytn/blob/dev/cmd/homi/setup/cmd.go#L302
* https://github.com/klaytn/klaytn/blob/dev/accounts/keystore/keystore.go#L543

`ks.ImportECDSA(pk, pwdStr)` function generates UTC-XXX file using `keyFileName` function.

I think that it cannot be expected that the function with prefix `Import` writes a file. Therefore, we must fix it not to generate files and make these steps to extract keystore data into `rewardN` files.

**Comment by odg0318** [comment]
@hqjang-pepper I created a PR. Please review my code overthere.

**Comment by hqjang-pepper** [comment]
Since following PR is merged, close this issue.
