### ISSUE TITLE
Implementing getTotalBurnt, getTotalCirculatingSupply API 

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1617]
**Background** 
Blockchain data services such as CoinMarketCap need to know the total burnt amount of KLAY and the total circulating supply.
They can calculate the number with on-chain data, however, it requires lots of time and engineering resources.
If we implement APIs for that information, they can quickly get it in anytime. 

**Consideration**
1. klay_getTotalBurnt
 - Two kinds of KLAY burning methods are used generally
   - KIP71 Burn mechanism: half of tx fee will be removed from the state 
   - Sending to `0xdead`: Anyone can send KLAY to `0xdead` address to burn KLAY
 - We can consider two types of returns depending on an input parameter 
   -  `klay_getTotalBurnt([Additional burn address])`: if `Additional burn address` is nil, return only the burnt amount by KIP71 Burn mechanism. With an input, we can add the balance of the input address  
 - We may need to store the data in the database. In that cases, find a safe way to calculate all previous block data

2. klay_totalCirculatingSupply
- We need to collect requirements and definition from data services or business team to define the specification

**Comment by smseo** [comment]
@aidan-kwon IMO, we should provide `klay_getTotalSupply`, not `klay_totalCirculatingSupply` because `klay_totalCirculatingSupply` might have to rely on offchain data. 

Let's first focus on `klay_getTotalBurnt` and `klay_getTotalSupply`.
cc @kjeom

**Comment by blukat29** [comment]
Implemented by #2148.
