### ISSUE TITLE
Private network

### ISSUE THREAD

**Issue by sneltyn** [klaytn/klaytn#1620]
```
ERROR[09/06,10:13:11 Z] [5] No genesis is provided. --networkid should be omitted if you want to 
use preconfigured network
Fatal: Error starting protocol stack: genesis block is not provided
```

I'm trying to run a private network. I use genesis.json from https://github.com/ethereum/go-ethereum#defining-the-private-genesis-state

**Comment by kjhman21** [comment]
Hi, @sneltyn Nice to meet you.
To run your own private network, please refer to this documentation:
https://docs.klaytn.foundation/node/service-chain/getting-started/4nodes-setup-guide

Thanks.
