### ISSUE TITLE
Gas fields update when recipient of internal call is EOA

### ISSUE THREAD

**Issue by jeongkyun-oh** [klaytn/klaytn#1621]
When the recipient of internal call is EOA, the `gas` / `gasUsed` fields are not shown in `callTracer` / `fastCallTracer`. This is due to hard implementation within the tracer. This should be updated.

cc @kjhman21 @aidan-kwon

**Comment by yoomee1313** [comment]
Might related to this klaytn forum post: https://forum.klaytn.foundation/t/klaytn-rpc-debug-traceblockbynumber/5944

**Comment by sjnam** [comment]
closed by #1953
