### ISSUE TITLE
got error when go mod vendor

### ISSUE THREAD

**Issue by esh2n** [klaytn/klaytn#1627]
**Describe the bug**

The problem is that go mod vendor does not vendor libsecp256k1/include/secp256k1.h referenced by crypto/secp256k1/curve.go.

**How to reproduce**
1. refer this repo.
2. go test -coverprofile=cover.out.tmp -v ./...

outputs:
```
# github.com/klaytn/klaytn/crypto/secp256k1
vendor/github.com/klaytn/klaytn/crypto/secp256k1/curve.go:48:10: fatal error: libsecp256k1/include/secp256k1.h: No such file or directory
   48 | #include "libsecp256k1/include/secp256k1.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Expected behavior**

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - Klaytn version or git revision that exhibits the issue `$ ken version`
 - go version `$ go version`
 
```
go version go1.17.5 darwin/arm64
```

 - OS and its version [e.g. macOS/10.14]
```
macOS/12.2
```

**Additional context**

**Comment by esh2n** [comment]
Solution:
add dummy file like this.

https://github.com/ethereum/go-ethereum/blob/master/crypto/secp256k1/dummy.go
https://github.com/ethereum/go-ethereum/blob/master/crypto/secp256k1/libsecp256k1/dummy.go
https://github.com/ethereum/go-ethereum/blob/master/crypto/secp256k1/libsecp256k1/include/dummy.go
Klaytn

**Comment by kjeom** [comment]
Thanks @esh2n.
I checked the same issue https://github.com/karalabe/usb/pull/17 in ethereum.
But I cannot reproduce the error with same environment of you.
Could you describe how to reproduce that in detail?

**Comment by aidan-kwon** [comment]
Close this since there are no responses for a long time
