### ISSUE TITLE
[Consensus] Imprecise consensus round value

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn#1628]
[The header struct contains a `extra` field which contains a round number value within one byte](https://github.com/klaytn/klaytn/blob/dev/blockchain/types/istanbul.go#L113). If a round number value exceeds one byte, an incorrect value would be inserted, but it does not affect to header verification process as long as all the committees run a binary that stores with one byte. It thus results in loss of precise round value and has an implication for associated APIs such as `klay_getBlockWithConsensusInfo()`. I guess the eight bytes of the vanity field may be reserved for precise `round` value representation without block extension like size or structural. Or, I'm not sure it does not need to be fixed as its value is not important on everywhere. 

cc. @jiseongnoh

**Comment by jiseongnoh** [comment]
Thank you for raising the issue.

As you mentioned, the round structure is uint64 on memory, but the block stores the value as one byte.
Please be noted that Klaytn consensus nodes wait for some amount of time when a round is added. 
The waiting time increases exponentially, so the round would not be increased be more than a few tens.
Also, there is a automatic node restart feature when a new block is not committed during some period (https://github.com/klaytn/klaytn/pull/476). When the nodes restart, the round resets to zero.
It is very unlikely that the round exceeds 255 (the maximum value of one byte data structure).

Even in a malicious case that some proposer sends very high round number(more than 255), 
the round number will be stored as truncated, and I believe there will be no side effect of the truncated round number.

Therefore, I believe the one-byte round value field will cause no significant problem, and will be safe to keep it as it is.
