### ISSUE TITLE
"Returning since the address is not a program account" INFO level logs are repeted.

### ISSUE THREAD

**Issue by KimKyungup** [klaytn/klaytn#1636]
In ISDev community, someone report this.
While syncing, this log was repeted.

I think we need to change the log level and check if the tx is inteded.

![image](https://user-images.githubusercontent.com/29390878/194708624-844859a7-21f9-4761-adeb-6392e97b94d5.png)

**Comment by kjhman21** [comment]
@jeongkyun-oh Seems like this is resolved? If it is, please close this issue.
