### ISSUE TITLE
[Verification] Ignoring validators' seals at the time of new governance effect

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn#1647]
The header verification does not lookup the required number of validators' seals when the governance data are filled in the header at every epoch (https://github.com/klaytn/klaytn/blob/dev/consensus/istanbul/backend/engine.go#L278).

Say epoch is one, the contained committees' seals are not verified at every block if any voting comes in every block, which means only the proposer's seal is enough to pass the validation. 

I tested with the following steps:
1. Generate any voting (any item) at every block.
2. Remove the `CommitedSeals` property of the block extra data in the header verification process and see the validation passes.  

Can anyone help me to understand why the seals are not verified at epochs?

cc. @jiseongnoh, @mckim19, @yoomee1313.

**Comment by jiseongnoh** [comment]
Thank you for raising the issue. It is a bug and the fix will be released soon.
Please refer to the other one https://github.com/klaytn/klaytn/issues/1548

**Comment by hyunsooda** [comment]
Okay, thank you.
