### ISSUE TITLE
Database compaction / pruning

### ISSUE THREAD

**Issue by t-anyu** [klaytn/klaytn#1660]
The database size is just growing. Other blockchain seems to implement ancient db or pruning features.

Have you considered implementing pruning that removes old data? It seems that all ENs are working as archive nodes, could this be changed?

Thanks

**Comment by kjhman21** [comment]
Hi, @t-anyu. thanks for creating an issue.

Here is the manual how to use state migration: https://medium.com/klaytn/klaytn-v1-5-0-state-migration-saving-node-storage-1358d87e4a7a

Also, we are implementing another technique that stores only storages for latest ranges of blocks. We expect that we can this feature as experimental soon. Thanks!
