### ISSUE TITLE
Issues for Milestone for v1.10.0 (Kore)

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1662]
New Features (hardfork)
- [KIP-81](https://github.com/klaytn/kips/pull/81): Implementing the on-chain governance voting method
  - #1375
  - #1615
- [KIP-82](https://github.com/klaytn/kips/pull/82): A New GC Reward Structure Due to Abolition of the Gini Coefficient
  - #1654 
  - #1657
- #1687
- #1663 
- #1664
- EVM changes
  - #1686
  - #1677
- Kore Hardfork config
  - #1639
  - #1640
  - #1668

Improvements
- #1111
- #1387 
- #1673 
- #1701 
- #1672 
- #1670 
- #1302
- Memory consumption reduction
  - #1216
  - #1136

Fixes
- getLogs
  - #1653 
  - #1710
- #1635 
- #1445 
- #1658 
- #1431
- #1206
- #1706

Miscellaneous
- #1636
- #1608
- #1605 
- #1594 
- #1616 
- #1682
- #1548
- #1697 
- #1587

Consideration
 - caver update to support
   - reward API support
   - governance_chainConfig

**Comment by blukat29** [comment]
Targetting v1.10.0-rc.3
- #1722
- #1723 
- #1724
- #1725 
- #1726 
- #1727 
- #1728 
  - #1729

**Comment by blukat29** [comment]
To be included in v1.10.0-rc.4 (Target date 2022-12-05)
- #1731

**Comment by blukat29** [comment]
To be included in v1.10.0-rc.5 (Target date 2022-12-12)

- #1736 
- coverage test fix

**Comment by aidan-kwon** [comment]
Related links
QA: https://github.com/klaytn/klaytn/issues/1676
Release: https://github.com/klaytn/klaytn/pull/1721
