### ISSUE TITLE
[Consensus] Transition from a validator to adversary

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn#1690]
cc. @jiseongnoh, @yoomee1313, @mckim19),

In short: Released validators can still send and receive consensus messages with the current validators.

I guess you guys already know the released validators cannot be a peer in view of committees ([https://github.com/klaytn/klaytn/blob/dev/node/cn/peer_set.go#L150](https://github.com/klaytn/klaytn/blob/dev/node/cn/peer_set.go#L150)). However, its validation seems to be considered only when a new node tries the handshake, which means, the released validators are still connected peers before the released validators leave the network. Also, the current validators still broadcast to released validators. (e.g., the preprepare messages are broadcasted to released peers). Thus, every broadcasting should have filtering so that its message can be sent to the proper receivers. Moreover, the released validator can still send messages to the current validators.

I tried round change attack, which would like to make a lot of round change so that the block generation could be delayed, but the benign implementation has a check of the required quorum for round change. However, the validators are still dangerous by numerous RPC request that takes a lot of memory and time and the attacker (released validator) can achieve the consensus delay.

The recommended modification I think is to add a condition that checks the current validator set to be received and sent messages. Also, the released validator should be removed from peer list on time where the governance (governance.removeValidator ) is triggered.

**Comment by yoomee1313** [comment]
@hyunsooda could you split this issue into two individual issues?

**Comment by hyunsooda** [comment]
Hi @yoomee1313, [posted here](https://github.com/klaytn/klaytn/issues/1695).
