### ISSUE TITLE
eth_getLogs - RPC doesn't support EIP-234 - log filtering by blockHash

### ISSUE THREAD

**Issue by SansegoTek** [klaytn/klaytn#1694]
RPC doesn't appear to support filtering logs by blockHash in eth_getLogs, instead returning logs for the most recently mined block

The following command will return logs for the most recently mined block, instead of the blockHash specified in the parameters:

```
curl https://public-node-api.klaytnapi.com/v1/cypress -X POST -H "Content-Type: application/json" --data \
'{"method":"eth_getLogs","params":[{"blockHash": "0xcb839977eb5226a2d0aea0f9b2b393e0beaa7a93f4beaea8af7f99e9dc3ce17a"}],"id":1,"jsonrpc":"2.0"}'
```

Instead, logs for the specified blocks should be returned, as per RPCs for other chains - e.g. 

```
curl https://polygon-rpc.com -X POST -H "Content-Type: application/json" --data \
'{"method":"eth_getLogs","params":[{"blockHash": "0x5f699b6ac8e172455343e7880f47000b5de51cd615a2fd0b55ec9eb937469aa2"}],"id":1,"jsonrpc":"2.0"}'
```

This seems to be the case on the public RPC, and our own internal node deployment:
 - Klaytn v1.9.1+8664bc8831
 - go version go1.17 linux/amd64
 - Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-107-generic x86_64)

**Comment by kjeom** [comment]
- https://github.com/klaytn/klaytn/pull/1653 could cover this issue.
