### ISSUE TITLE
The problem that the ken program memory only increases but does not decrease.

### ISSUE THREAD

**Issue by sundafa** [klaytn/klaytn#1703]
**Describe the bug**
The memory will continue to increase (the limit parameter is invalid), until the system memory bursts and crashes.
I think it's a database problem.
I also encountered the problem that the memory could not be released when using `badger_database` in our project, and then replaced other databases to solve it.

**How to reproduce**
Keep running commands, or keep requesting rpc nodes.
cmd: `/usr/local/bin/ken --cypress --datadir /node/full/klaytn/ --syncmode full --gcmode full --multichannel --srvtype fasthttp --txpool.exec-slots.all 4096 --txpool.nonexec-slots.all 4096 --txpool.exec-slots.account 4096 --txpool.nonexec-slots.account 4096 --rpc --rpcaddr "0.0.0.0" --rpc.concurrencylimit 60000 --rpcapi "debug,klay,eth,personal,rpc,txpool,web3,net,trace" --rpccorsdomain "*" --rpcvhosts "*" --ws --wsaddr "0.0.0.0" --wsapi "debug,klay,eth,personal,rpc,txpool,web3" --wsorigins "*" --metrics --prometheus --port 31270 --rpcport 31271 --wsport 31272 --subport 31274 --prometheusport 31275 --state.trie-cache-limit 10240`

**Expected behavior**
Limits memory and does not increase when limit is reached.
Or automatically release memory under low load.

**Attachments**
The monitoring shows that the service's sudden increase in memory usage causes the system to become unresponsive
![image](https://user-images.githubusercontent.com/24621599/202066617-40272d20-879d-4bd4-95e6-516a3d6844bd.png)

**Environment (please complete the following information)**
 - Klaytn v1.9.1+8664bc8831
 - go version go1.19.2 linux/amd64
 - Ubuntu 20.04

**Additional context**

**Comment by sundafa** [comment]
Under the limit of this parameter `--state.trie-cache-limit 10240`, the memory is still growing slowly, and this server has occupied 99947K of memory
![image](https://user-images.githubusercontent.com/24621599/202069870-700cec84-8d48-46b5-b22c-0daa4b1d857e.png)

**Comment by yoomee1313** [comment]
I think your concurrency limit is too big compared to Ram size. Our recommend(default) is 3000. Were you syncing or were you serving rpc requests?

**Comment by sundafa** [comment]
As rpc server

**Comment by yoomee1313** [comment]
How much was the load? And what kind of load was it?

**Comment by sundafa** [comment]
This server with 256G memory is now at 9% load.
But on other servers with relatively small memory, such as 64G,ken memory growth will reach 80% memory, and finally the system will crash due to insufficient memory

**Comment by yoomee1313** [comment]
We have changed the default RPC server type from fasthttp to http at v1.10.2. rpcconcurrencylimit only affects fasthttp server.
