### ISSUE TITLE
Can't relax the limitations of TxMaxSize?

### ISSUE THREAD

**Issue by brew0722** [klaytn/klaytn#1732]
I understand that the current Mempool Tx size limitation of Klaytn is 32KB.
And in the case of ethereum, it's 4x as much as 128KB.
Due to this difference, some open-source contracts are deployed and executing well on Ethereum, but deployment fails on klaytn.

It is difficult to attempt optimization, such as dividing contracts.
There are cases where it is difficult to respond due to issues such as licenses.

I understand that this limitation has not changed since the initial commit.
Could you relax this limitation? If it has been reviewed internally, please share it.

https://github.com/klaytn/klaytn/blob/e5c4ae5030cd8ef12acbc7052781993d76015b5b/blockchain/tx_pool.go#L51

https://github.com/ethereum/go-ethereum/blob/1b8a392153b39fbbde17536c730d96510e57341f/core/txpool/txpool.go#L54

**Comment by kjhman21** [comment]
Hi, @brew0722 . Thanks for creating this issue.
We tried to include this in the current release, but it is not good time to do that right now.
We will include this change in the next version.
Sorry for any inconvenience.

**Comment by brew0722** [comment]
@kjhman21  That's okay. I prefer stable development over time. 
Thank you for actively resolving the issue.

 I look forward to next release.

**Comment by yoomee1313** [comment]
v1.10.2 has been released so close this issue. cc. @brew0722 @kjhman21
If there's any problem, please reopen this issue.
