### ISSUE TITLE
Can the klaytn data be pruned？

### ISSUE THREAD

**Issue by zhy827827** [klaytn/klaytn#1740]
i want to pruned data,But I can't find the corresponding document。Who can help me?

**Comment by kjhman21** [comment]
Hi, @zhy827827. Thanks for filing a question here.

You can find pruned data with this URL:

https://docs.klaytn.foundation/installation-guide/deployment/endpoint-node/installation-guide/configuration#fast-sync-optional

Hope this helps.

**Comment by zhy827827** [comment]
Only the downloaded snapshot data and replaced original data?

**Comment by kjhman21** [comment]
@zhy827827 This documentation tells you how to change the chaindata. Hope this helps.
https://docs.klaytn.foundation/content/operation-guide/chaindata-change

**Comment by zhy827827** [comment]
ok,thankccc~~~~

**Comment by kjhman21** [comment]
Solved. Closing this issue.
