### ISSUE TITLE
QA for v1.10.1

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1750]
We have reported that Klaytn v1.10.0 has issues in specific situations. We are going to prepare v1.10.1 for a hotfix version soon to mitigate them.

- Issue 1) fasthttp hadler panic during parsing a user’s RPC request body in a specific situation
- issue 2) Governance config related panic issue that can be triggered when a node client downgrades its version (v.1.10 -> 1.9.x). 

## Patches and tests
Issue 1) 
- Patch: https://github.com/klaytn/klaytn/pull/1752
- Tests
  - No additional test is required if disabling StreamRequestBody is the correct patch. The option was not used before v1.10.0, so RPC test automatically being executed for release is enough for it.

Issue 2) 
- Patch: https://github.com/klaytn/klaytn/pull/1749
- Tests
  - Manual tests are required for [this patch](https://github.com/klaytn/klaytn/pull/1749). The effect of the change is small, so we can consider following scenarios
  - WriteGovernanceState in JSON with v1.9.1, andReadGovernanceState  with v1.10.1
  - WriteGovernanceState in JSON with v1.10.0, andReadGovernanceState  with v1.10.1
  - WriteGovernanceState in JSON with v1.10.1, andReadGovernanceState  with v1.9.1
  - WriteGovernanceState in JSON with v1.10.1, andReadGovernanceState  with v1.10.1

**Comment by ian0371** [comment]
v1.9.1 <-> v1.10.0 <-> v1.10.1 test
- v1.9.1 -> v1.10.1: ✅ (governanceState.chainConfig = Some)
- v1.10.0 -> v1.10.1: ✅ (governanceState.chainConfig = nil -> Some)
- v1.10.1 -> v1.9.1: ✅ (governanceState.chainConfig = Some)
- v1.10.1 -> v1.10.0: ✅ (governanceState.chainConfig = Some -> nil)
