### ISSUE TITLE
Can the klaytn data be pruned？

### ISSUE THREAD

**Issue by YuXiaoCoder** [klaytn/klaytn#1751]
The current running node requires a lot of disk space. Is it possible to support pruning of historical data?

**Comment by aidan-kwon** [comment]
Yes. 
You can prune old state data using `stateMigration` feature described in [here](https://docs.klaytn.foundation/content/operation-guide/chaindata-migration).  The feature provides runtime state pruning, so you can operate Klaytn node during the pruning time. However, it takes lots of memory and time for runtime pruning. 

If you think `stateMigration` takes too much resources or time, then you can consider chaindata change with the latest chaindata snapshot described [here](https://docs.klaytn.foundation/content/operation-guide/chaindata-change). The chaindata snapshot is pruned periodically, so you can download the latest snapshot and replace your current data.
