### ISSUE TITLE
[Governance] Incorrect value returning of `governance.itemsAt`.

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn#1775]
[hyunsooda created:] 
**Describe the bug**
The `governance.itemsAt()` function internally calls the `ParamsAt()` function, and its base epoch value is not an exact value. [Instead, it is fetched from the current parameter set, which may result in an imprecise governance configuration](https://github.com/klaytn/klaytn/blob/dev/governance/default.go#L1233). For example, if the initial epoch is set to 10 at the genesis block, and if the `governance.epoch` is voted to 2 at block number 2, the update is applied at block number 20. However, when calling the `itemsAt()` API with a block number parameter of 12, the API returns the updated settings, even though the update was applied at block 20. This is because the epoch value is incorrectly fetched, leading to inconsistent results. To resolve this issue, the epoch value must be correctly fetched.

**How to reproduce**
Refer to the bug description

**Expected behavior**
Refer to the bug description

**Attachments**

**Environment (please complete the following information)**
- OS: Linux distribution
- Version: latest `dev` branch

**Additional context**

**Comment by sjnam** [comment]
@hyunsooda 
This api `governance.itemsAt` is no longer used by pr #1860
This issue can be closed.
