### ISSUE TITLE
Data size of official snapshot for KEN has increased too much

### ISSUE THREAD

**Issue by mrhe117** [klaytn/klaytn#1781]
As a node operator, we termly download the official snapshot for KEN to keep the data storage size of the node from here: https://packages.klaytn.net/cypress/chaindata/
But a new snapshot is always much bigger than the old one. And it increased rapidly. As a result, we need to frequently change the hardware's specs to be with bigger storage. The cost increases as well. 
Could you control the data-increasing speed of the snapshots? This is beneficial for the community to run KEN.

**Comment by kjhman21** [comment]
@mrhe117 Thanks for sharing your concern.
We have been looking for solutions in various aspects to reduce storage size, and I hope that we will share some solutions in 2Q.
We have been researching the method to store the values of the latest world state of the blockchain. It's too deep tech to explain everything in a short story, so please wait for some more month until we finalize the implementation. Thanks.
