### ISSUE TITLE
QA for v1.10.2

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1802]
### Protocol Upgrade
- KGP-6 Implementation @ian0371 @aidan-kwon 
  - #1809 
  - #1810
  - #1812
    - [ ] https://github.com/klaytn/klaytn/issues/1802#issuecomment-1467241018

### Improvements
- Build optimization - no test required
  - #1764 
  - #1769 
- Increase tx max size - @yoomee1313 
  - #1747 
  - #1748
  - #1733 
    - [x] https://github.com/klaytn/klaytn/issues/1802#issuecomment-1455717938
- Governance - @blukat29 
  - #1767 
  - #1772
  - #1779
  - #1782
  - #1783
  - #1785
  - #1791
    - [x] https://github.com/klaytn/klaytn/issues/1802#issuecomment-1447738774
- Consensus - @blukat29 
  - #1787
    - [x] https://github.com/klaytn/klaytn/issues/1802#issuecomment-1455408593
- Debug trace RPC - @blukat29 
  - #1762
    - [x] https://github.com/klaytn/klaytn/issues/1802#issuecomment-1455411405
- APIs - @blukat29 
  - #1778
  - #1789
  - #1792
    - [x] https://github.com/klaytn/klaytn/issues/1802#issuecomment-1457684720
- RPC fix - @JayChoi1736 
  - #1786 

### Fixes
- #1766 - @ian0371 
	- [x] https://github.com/klaytn/klaytn/issues/1802#issuecomment-1457414687 
- #1771 - @ian0371 
	- [x] https://github.com/klaytn/klaytn/issues/1802#issuecomment-1457629539
- #1765 - @kjeom 

### Misc
- #1745 
- #1757 
- #1768

### Regular tests 

- [ ] https://github.com/klaytn/klaytn/issues/1802#issuecomment-1455339354 - @JayChoi1736 

### Other updates

- caver-js update
- caver-java update
- klaytn-docs update

**Comment by ian0371** [comment]
- Governance parameters vote test

| Parameter name | before | after | how to check | pre-Kore activation | post-Kore activation |
| --- | --- | --- | --- | --- | --- |
| istanbul.committeesize | 13 | 4 | klay.getCommittee() |  |  |
| governance.unitprice | 25 ston | 10 ston | klay.gasPriceAt() |  |  |
| governance.deriveshaimpl | 2 | 0 | klay.getBlock().transactionsRoot |  |  |
| governance.govparamcontract | 0x0 | deployed address | Place setParam(deriveshaimpl) on GovParam and then vote |  |  |
| reward.mintingamount | 9.6 KLAY | 6.4 KLAY | klay.getRewards() |  |  |
| reward.ratio | 34/54/12 | 50/40/10 | klay.getRewards() |  |  |
| reward.useginicoeff | false | true | [4m 5m 6m 7m]  stakes klay.getRewards() |  |  |
| reward.kip82ratio | 20/80 | 100/0 | [4m 5m 6m 7m]  stakes klay.getRewards() |  |  |
| reward.deferredtxfee | true | false | check using #1692 bug klay.getRewards() fee: 150% |  |  |
| reward.minimumstake | 5m | 6m | [4m 5m 6m 7m]  stakes klay.getCommittee() |  |  |
| kip71.lowerboundbasefee | 25 ston | 50 ston | klay.getBlock() |  |  |
| kip71.upperboundbasefee | 750 ston | 500 ston | Using gas fee bufner, increase the gas price to max and check with klay.getBlock() |  |  |
| kip71.gastarget | 30m | 20m | Use gas fee burner before and after activation |  |  |
| kip71.basefeedenominator | 20 | 10 | Use gas fee burner before and after activation |  |  |
| kip71.maxblockgasusedforbasefee | 60m | 80m | Use gas fee burner before and after activation |  |  |
| governance.governancemode | - | - | - | - | - |
| governance.governingnode | - | - | - | - | - |
| istanbul.epoch | - | - | - | - | - |
| istanbul.policy | - | - | - | - | - |
| reward.stakingupdateinterval | - | - | - | - | - |
| reward.proposerupdateinterval | - | - | - | - | - |
| governance.addvalidator | - | - | - | - | - |
| governance.removevalidator | - | - | - | - | - |
| param.txgashumanreadable | - | - | - | - | - |
| istanbul.timeout | - | - | - | - | - |

**Comment by blukat29** [comment]
Consensus committed seal count test

Inspect `klay.getBlock(num).extraData` to see how many seals (signatures) are in the block.
- Modify councilSize by governance.vote(governance.removevalidator)
- Modify committeeSize by governance.vote(istanbul.committeesize) 

| > councilSize<br>V committeeSize | 1 | 2 | 3 | 4 |
|----------------------------------|---|---|---|---|
| 1                                |   |   |   |   |
| 2                                |   |   |   |   |
| 3                                |   |   |   |   |
| 4                                |   |   |   |   |

**Comment by blukat29** [comment]
Debug trace timeout test
- Prevent accidental DoS
  - Create large Tx using [klaytn-burst-fee-test](https://github.com/blukat29/klaytn-burst-fee-test)
  - Call `debug.traceTransaction(txid)`
- Allow custom timeout
  - Call `debug.traceTransaction(txid, {loggerTimeout:"XXms"})`

**Comment by yoomee1313** [comment]
transaction size test
Tx size | accepted | log
-- | -- | --
16KB | |
32KB | |
127KB | | 
256KB | |

**Comment by ian0371** [comment]
"Missing trie node" bug fix test

How to reproduce the environment where header chain is ahead of block chain
- Spawn 1CN-1EN
- connect EN to CN (`admin.addPeer()`) and sync more than 128 blocks
- stop EN (`docker-compose stop EN-0`)
- respawn EN (`docker-compose start EN-0`)
- connect EN to CN (`admin.addPeer()`)

If the log contains following messages, it's successful.

```
INFO[03/07,02:38:00 Z] [5|blockchain/blockchain.go:499]              Loaded most recent local header           number=140 hash=5160b9…a2fe77 td=141 age=7s
INFO[03/07,02:38:00 Z] [5|blockchain/blockchain.go:500]              Loaded most recent local full block       number=140 hash=5160b9…a2fe77 td=141 age=7s1ms
INFO[03/07,02:38:00 Z] [5|blockchain/blockchain.go:501]              Loaded most recent local fast block       number=140 hash=5160b9…a2fe77 td=141 age=7s1ms
WARN[03/07,02:38:00 Z] [5|blockchain/blockchain.go:310]              Head state missing, repairing chain       number=140 hash=0x5160b9b6b2e2c258d04063c705d9c03d1875f6d34a1f2b1f557ee0b24ca2fe77
INFO[03/07,02:38:00 Z] [5|blockchain/blockchain.go:499]              Loaded most recent local header           number=140 hash=5160b9…a2fe77                                                      td=141 age=7s7ms
INFO[03/07,02:38:00 Z] [5|blockchain/blockchain.go:500]              Loaded most recent local full block       number=128 hash=e8abee…f5fe10                                                      td=129 age=7s7ms
INFO[03/07,02:38:00 Z] [5|blockchain/blockchain.go:501]              Loaded most recent local fast block       number=140 hash=5160b9…a2fe77                                                      td=141 age=7s7ms
```

**Comment by ian0371** [comment]
klay_getRewards() invariant test

- [ ] check if `klay_getRewards()` stick to the invariant `minted + totalFee - burntFee = proposer + stakers + kgf + kir`
  - [ ] when stakes are [5m+1, 5m+6, 5m]

**Comment by blukat29** [comment]
Check API for fund name changes
- [x] `klay_getRewards()` returns `kff kcf` only
- [x] `governance_getStakingInfo()` returns both `PocAddr KIRAddr` and `kffAddr kcfAddr`

**Comment by aidan-kwon** [comment]
Treasury Rebalancing Test
- local test @blukat29 @ian0371 @aidan-kwon 
- Baobab single node test @aidan-kwon
