### ISSUE TITLE
Is there a memory leak issue in version 1.10.2?

### ISSUE THREAD

**Issue by sjlee1125** [klaytn/klaytn#1827]
We have two Klaytn nodes, and each node is used as a target group for application load balancing.
We updated from version 1.10.1 to 1.10.2 to support the Kore hard fork.
However, since then, the available memory for the target group keeps decreasing, leading to either process termination or instance failure due to memory shortage.
Is there a memory leak issue in version 1.10.2?

here are available memory grafana dashboards.
[first node]
![image](https://user-images.githubusercontent.com/47561537/232416653-d9f6c085-5639-43ff-8809-f691e26c421a.png)
[second node]
![image](https://user-images.githubusercontent.com/47561537/232416980-c9d0ab46-7a66-416b-9794-94ae1947a01a.png)

**Comment by sjlee1125** [comment]
@aidan-kwon
we use several rpc methods.
here is list
```
debug_traceBlockByNumber
klay_getBlock
klay_getBlockNumber
klay_getLogs
klay_getTransactionReceipt
klay_getTransaction
klay_getBalance
klay_call
klay_sendRawTransaction
klay_getTransactionCount
```

**Comment by yoomee1313** [comment]
@sjlee1125 Hi, can I ask several questions? It would be help to figure out the problem.
* Could you share your node spec? (memory size, cpu, storage spec, etc)
* Did you build the binary yourself? If it is, which go version you used?
* There is a point where the memory suddenly increase. Did rpc calls start coming in from that point? It would be better if you could share the overall history.

**Comment by sjlee1125** [comment]
@yoomee1313 Thank you for answer

We are currently using an AWS m5.xlarge instance with specifications of 4 cores and 16GB of memory. Although we are aware that the recommended specifications for version 1.10.1 indicate 8 cores and 64GB of memory, we have been able to use the m5.xlarge instance without any issues.

We used the pre-built binary from https://packages.klaytn.net/klaytn/v1.10.2/ken-v1.10.2-0-linux-amd64.tar.gz without building it ourselves.

As soon as RPC calls started coming in, we noticed a sharp increase in memory usage that did not decrease. We suspect that there may be a memory leak in one of the calls we make per block, such as klay_getBlock, klay_getBlockNumber, or klay_getLogs.

**Comment by yoomee1313** [comment]
Thanks very much. It takes some time to check the issue, but I'll come back as soon as possible if an update is made. Can I just check one more thing? Do you know which tracer is used for traceBlockByNumber api and how often the api is called?

**Comment by sjlee1125** [comment]
we use fastCallTracer for debug_traceBlockByNumber

**Comment by sjlee1125** [comment]
@yoomee1313 Did you find someting?

**Comment by yoomee1313** [comment]
@sjlee1125 Sorry for the late answer. We've tried to reproduce the issue by calling getLogs and traceTransaction at rates of 10, 100, and 1,000 times per second, but the issue of continuous memory increase didn't easily recur. It seems that I might need some analysis information from you. Would it be possible for you to conduct profiling at the point when the memory is increasing?

**Comment by sjlee1125** [comment]
@yoomee1313 I'm sorry for the delayed response. It seems like the issue was specific to our node, so I took a snapshot and launched a new node, and the problem disappeared. Thank you for your understanding and assistance.

**Comment by yoomee1313** [comment]
@sjlee1125 I'm glad there were no issues. If same issue occurs again, please reopen this issue.
