### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Andrew-Pohl** [klaytn/klaytn#1841]
**Describe the bug**
We noticed that occasionally eth_calls on an RPC endpoint was returning incorrect data inconsistently (when compared with other nodes we run). When looking through the logs we noticed an instance of the log line:

"[48] Unexpected error while reading cached trie node"

shortly followed by an invalid memory address or nil pointer dereference (I assume these are related) 

stack trace below:

"May 09 18:32:17 klaytn ken[2021685]: ERROR[05/09,18:32:17 Z] [39] RPC method eth_getBlockByNumber crashed: runtime error: invalid memory address or nil pointer dereference
May 09 18:32:17 klaytn ken[2021685]: goroutine 3681 [running]:
May 09 18:32:17 klaytn ken[2021685]: [github.com/klaytn/klaytn/networks/rpc.(*callback).call.func1(0xc04e273120](http://github.com/klaytn/klaytn/networks/rpc.(*callback).call.func1(0xc04e273120), 0x14, 0xc03cf44d78)
May 09 18:32:17 klaytn ken[2021685]:         /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/service.go:211 +0xba
May 09 18:32:17 klaytn ken[2021685]: panic(0x1b42720, 0x2ea61f0)
May 09 18:32:17 klaytn ken[2021685]:         /usr/local/go/src/runtime/panic.go:969 +0x1b9
May 09 18:32:17 klaytn ken[2021685]: [github.com/klaytn/klaytn/work.(*worker).pendingBlock(0xc0238d4160](http://github.com/klaytn/klaytn/work.(*worker).pendingBlock(0xc0238d4160), 0x0)
May 09 18:32:17 klaytn ken[2021685]:         /ext-go/1/src/github.com/klaytn/klaytn/work/worker.go:230 +0x10e
May 09 18:32:17 klaytn ken[2021685]: [github.com/klaytn/klaytn/work.(*Miner).PendingBlock(0xc02c2cfe50](http://github.com/klaytn/klaytn/work.(*Miner).PendingBlock(0xc02c2cfe50), 0x167b8000000000)
May 09 18:32:17 klaytn ken[2021685]:         /ext-go/1/src/github.com/klaytn/klaytn/work/work.go:219 +0x2f
May 09 18:32:17 klaytn ken[2021685]: [github.com/klaytn/klaytn/node/cn.(*CNAPIBackend).BlockByNumber(0xc02308e730](http://github.com/klaytn/klaytn/node/cn.(*CNAPIBackend).BlockByNumber(0xc02308e730), 0x211a0e0, 0xc04e6d9e40, 0xfffffffffffffffe, 0x211a0e0, 0xc04e6d9e40, 0xc03cf44978)
May 09 18:32:17 klaytn ken[2021685]:         /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_backend.go:127 +0x16b
May 09 18:32:17 klaytn ken[2021685]: [github.com/klaytn/klaytn/api.(*EthereumAPI).GetBlockByNumber(0xc012129b40](http://github.com/klaytn/klaytn/api.(*EthereumAPI).GetBlockByNumber(0xc012129b40), 0x211a0e0, 0xc04e6d9e40, 0xfffffffffffffffe, 0x0, 0x0, 0x0, 0x0)
May 09 18:32:17 klaytn ken[2021685]:         /ext-go/1/src/github.com/klaytn/klaytn/api/api_ethereum.go:475 +0x73
May 09 18:32:17 klaytn ken[2021685]: reflect.Value.call(0xc02c289d00, 0xc02bba3f00, 0x13, 0x1de0a3c, 0x4, 0xc04ea88120, 0x4, 0x4, 0xc04ea88150, 0xc04e6e7860, ...)
May 09 18:32:17 klaytn ken[2021685]:         /usr/local/go/src/reflect/value.go:476 +0x8c7
May 09 18:32:17 klaytn ken[2021685]: reflect.Value.Call(0xc02c289d00, 0xc02bba3f00, 0x13, 0xc04ea88120, 0x4, 0x4, 0xc04e26e270, 0x2, 0x2)
May 09 18:32:17 klaytn ken[2021685]:         /usr/local/go/src/reflect/value.go:337 +0xb9
May 09 18:32:17 klaytn ken[2021685]: [github.com/klaytn/klaytn/networks/rpc.(*callback).call(0xc01e3c2240](http://github.com/klaytn/klaytn/networks/rpc.(*callback).call(0xc01e3c2240), 0x211a0e0, 0xc04e6d9e40, 0xc04e273120, 0x14, 0xc04e6e7860, 0x2, 0x2, 0x0, 0x0, ...)
May 09 18:32:17 klaytn ken[2021685]:         /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/service.go:217 +0x2c5
May 09 18:32:17 klaytn ken[2021685]: [github.com/klaytn/klaytn/networks/rpc.(*handler).runMethod(0xc039ff7480](http://github.com/klaytn/klaytn/networks/rpc.(*handler).runMethod(0xc039ff7480), 0x211a0e0, 0xc04e6d9e40, 0xc04ea8c000, 0xc01e3c2240, 0xc04e6e7860, 0x2, 0x2, 0x2)
May 09 18:32:17 klaytn ken[2021685]:         /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/handler.go:422 +0x9b
May 09 18:32:17 klaytn ken[2021685]: [github.com/klaytn/klaytn/networks/rpc.(*handler).handleCall(0xc039ff7480](http://github.com/klaytn/klaytn/networks/rpc.(*handler).handleCall(0xc039ff7480), 0xc04e6e7800, 0xc04ea8c000, 0x1b9d520)
May 09 18:32:17 klaytn ken[2021685]:         /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/handler.go:370 +0x297
May 09 18:32:17 klaytn ken[2021685]: [github.com/klaytn/klaytn/networks/rpc.(*handler).handleCallMsg(0xc039ff7480](http://github.com/klaytn/klaytn/networks/rpc.(*handler).handleCallMsg(0xc039ff7480), 0xc04e6e7800, 0xc04ea8c000, 0x2101301)
May 09 18:32:17 klaytn ken[2021685]:         /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/handler.go:333 +0x1ff
May 09 18:32:17 klaytn ken[2021685]: [github.com/klaytn/klaytn/networks/rpc.(*handler).handleMsg.func2(0xc04e6e7800)](http://github.com/klaytn/klaytn/networks/rpc.(*handler).handleMsg.func2(0xc04e6e7800))
May 09 18:32:17 klaytn ken[2021685]:         /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/handler.go:165 +0x46
May 09 18:32:17 klaytn ken[2021685]: [github.com/klaytn/klaytn/networks/rpc.(*handler).startCallProc.func1(0xc039ff7480](http://github.com/klaytn/klaytn/networks/rpc.(*handler).startCallProc.func1(0xc039ff7480), 0xc04e6fdba0)
May 09 18:32:17 klaytn ken[2021685]:         /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/handler.go:255 +0x102
May 09 18:32:17 klaytn ken[2021685]: created by [github.com/klaytn/klaytn/networks/rpc.(*handler).startCallProc](http://github.com/klaytn/klaytn/networks/rpc.(*handler).startCallProc)
May 09 18:32:17 klaytn ken[2021685]:         /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/handler.go:250 +0x9c"

The node then restarts and continues to run without any issues and remains insync but occasionally still returns incorrect data.

**Attachments**
see stack trace above

**Environment**
 - Klaytn version: Klaytn v1.10.2+2dc0b6578b
 - OS: Ubuntu 22.04 LTS

**Comment by aidan-kwon** [comment]
Thank you for reporting. 

It seems that you are inputting "pending" block as a block number parameter when you're calling APIs. I think you will not have the issue if you are using "latest" block as a block number parameter. 
Klaytn has separated the role of nodes into various types; block generation node (CN) and API serving node (EN), and others. Probably, you're node type is EN, so it doesn't generate a block and cannot handle "pending" block (self-generated block but not confirmed by other nodes) correctly. 

Please try with "latest" block parameter and share your result. 
I will fix Klaytn code as well not to cause the same issue even though a user is using the "pending" keyword in the next version.

**Comment by Andrew-Pohl** [comment]
Thanks for the reply, sadly this is a public facing node so not easy to do as a work around we will drop all requests containing pending in the data before passing it to the node, until their is an offical fix in #1842 

I assume this is also unrelated to the issue I mentioned with incorrect data being served?.

**Comment by aidan-kwon** [comment]
@Andrew-Pohl Regarding the panic log, you will not see the same panic log anymore if you cherry-pick #1847 on top of the recent version v1.10.2.

About the incorrect response of `eth_call`, I don't think it is related to the panic log and my fix. 
In most cases, the inconsistency between nodes is caused by the block number difference. Usually, users use `eth_call` without the specific block number. Then, the node executes the request at the latest block. If two nodes have different block heights at the time of API execution, the responses can be different because the contract data is updated. 

If your case is different from the above explanation, please share more information about your request. Then, I will analyze more with you :)
