### ISSUE TITLE
[AddressBook] A same request cannot be created

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn#1844]
**Describe the bug**
In the current implementation of the AddressBook, it is not possible to create the same request multiple times. All the external functions in the AddressBook contract check the id, which is a hash of the function name and parameters. If the same id is provided as input later, the function never get executed (transaction is not reverted without explicit error).

Let's consider an execution path as an example: (1) register CnStakingV2 contract -> (2) unregister CnStakingV2 contract -> (3) register CnStakingV2 contract. If the inputs for (1) and (3) are the same (i.e., the same CN address, CnStaking contract address, and reward address), the execution of (3) will not be carried out without explicitly returning an error.

To explain this logically, let's assume an initial state `s`, and the result of executing (1) is state `s'`. Then, the result of executing (2) is state `s`, which brings us back to the initial state. Therefore, the execution of (3) should be successful and yield the state `s'`, which is the same as the result of executing (1).

**How to reproduce**
Take the execution path provided above

**Expected behavior**
If both the input and the current state are considered valid, the same request should be handled correctly.

**Attachments**

**Environment (please complete the following information)**

**Additional context**

**Comment by ian0371** [comment]
Recently we had this issue:
https://scope.klaytn.com/tx/0x3b4f88d1f5f90333ae1eddc210d864a4d42bfcf604fadcee44fa38554495ac76?tabId=internalTx

After 2 weeks from the original request, it is removed so you can resend it.

Currently, there seems to be no way to address this issue.

**Comment by hyunsooda** [comment]
Ah, I apologize for not noticing this functionality earlier. Checked now.
