### ISSUE TITLE
Adjusting computation cost and OpcodeComputationCostLimit

### ISSUE THREAD

**Issue by aidan-kwon** [klaytn/klaytn#1849]
The computation cost of opcodes and OpcodeComputationCostLimit was calculated based on the benchmark results in an AWS machine. Since the overall hardware performance has increased compared to 4 years ago, we need to measure the computation cost of each opcode again and adjust the values and OpcodeComputationCostLimit.

Tasks
- [ ] Measure the performance of each opcode based on the recent Cypress data
- [ ] Adjust OpcodeComputationCostLimit to accomplish 1-second finality in the recommended HW spec EN
- [ ] Adjust the computation cost of each opcode 

Notice 
- This change requires a hardfork upgrade 
- We may need to write KIP for this computation cost change

**Comment by blukat29** [comment]
Completed with https://github.com/klaytn/klaytn/pull/2037.
