### ISSUE TITLE
Could you consider supporting debug_tracecall?

### ISSUE THREAD

**Issue by brew0722** [klaytn/klaytn#1870]
**Is your request related to a problem? Please describe.**
As you know, `debug_tracecall`, like `eth_call`, enables simulation in the latest state. 
actually, my need started from wanting to simulate event logging beyond the return value.
However, I understand that this is not easy to do, even with `debug_tracecall` support.

The reason propose an issue is because recent 4337 AA bundler implementations use `debug_tracecall` to implement the simulation and [banned opcode specification](https://eips.ethereum.org/EIPS/eip-4337#forbidden-opcodes).
Given the many advantages of klaytn network, there are fewer reasons to use 4337 AA, but my personal opinion is that will continue to see more solutions that to be used the simulation.

Maybe it is not possible to match geth and trace output in the current implementation of klaytn.
Just I am suggesting this without knowing the details of the difference, so please consider it carefully.

**Describe the solution you'd like**

**Describe alternatives you've considered**

Maybe it is not possible to match geth and trace output in the current implementation of klaytn.
Just I am suggesting this without knowing the details of the difference, so please consider it carefully.

**Additional context**
As far as I can tell, the reference, stackup, and voltaire bundler implementations use the `debug_tracecall` rpc api to implement the simulation specs. There may be other bundlers as well.

**Comment by aidan-kwon** [comment]
@brew0722 Thank you for suggesting `debug_traceCall` implementation. Definitely, we will support the API soon.

**Comment by aidan-kwon** [comment]
@yoomee1313 Please, take this issue and implement `debug_traceCall` and the following tasks such as supporting state overriding.
