### ISSUE TITLE
[Homi] Homi usage is incompatible between v1.10.2 and v.1.11.0-rc.2

### ISSUE THREAD

**Issue by hyunsooda** [klaytn/klaytn#1936]
### Problem
This may be a minor issue. The `homi` had been taken `gen-type` flag. This flag could be passed with 'argument', not 'flag' until v1.10.2 such as `./homi setup local --baobab-test --cn-num 1`

The discrepency in the version of `v1.11.0-rc.2` did not correctly parse all the flags, appeared after `argument`, which ls the `local` in the example above. Thus, `--cn-num` should be zero.

There are two alternative ways. (1) Explicitly pass with the flag like `./homi setup --gen-type local --baobab-test --cn-num 1`. Or, (2) Pass to the `arugment` to the end of the line `./homi setup  --baobab-test --cn-num 1 local`

### Implication
The command listed in docs seems to be refined by this incompatible usages. e.g., https://ko.docs.klaytn.foundation/content/installation-guide/deployment/service-chain/getting-started/4nodes-setup-guide. 

### Reference
- https://github.com/temporalio/tctl/issues/323
- https://github.com/buildkite/agent/pull/1286
- https://github.com/urfave/cli/issues/1481
- https://stackoverflow.com/questions/73587275/urfave-cli-argument-placement-prevents-flag-parsing

**Comment by blukat29** [comment]
Hi @hyunsooda, as in the links you've posted, the change comes from the urfave/cli v2 upgrade.
We upgraded to v2 so klaytn binary can parse YAML files with hierarchy (#1684).

You are correct, `homi` has to be used in alternative ways (1) and (2).
Klaytn docs should be updated accordingly. Thanks for the report.

**Comment by hyunsooda** [comment]
Closed via https://github.com/klaytn/klaytn-docs/pull/582
