### ISSUE TITLE
Run the pruning node

### ISSUE THREAD

**Issue by YuXiaoCoder** [klaytn/klaytn#1943]
Can you please tell me how to run nodes that can be pruned in real time using v1.11.0 for reducing disk usage, currently I'm running v.1.10.2 version of the node which is already taking up 5T in size!

This is the data occupancy of my current node's chaindata directory
```bash
/mnt/klaymain/node/klay/chaindata# du -sh *
839G	body
700K	bridgeservice
290G	header
16G	misc
1020G	receipts
71G	snapshot
2.7T	statetrie_migrated_84482070
130G	txlookup
```

The command to run the service is
```bash
/opt/klaymain/core/ken --cypress --snapshot --datadir=/mnt/klaymain/node --syncmode=full --gcmode=full --rpc --
rpcapi=klay,admin,eth,net,web3,debug --rpcport=8545 --rpcaddr=0.0.0.0 --rpccorsdomain=* --rpcvhosts=* --ws --wsapi=klay,admin,eth,net,web3,debug --wsport=8546 --wsaddr=0.0.0.0 --
wsorigins=* --port=30303 --srvtype=fasthttp --verbosity=3 --txpool.exec-slots.all=4096 --txpool.nonexec-slots.all=4096 --txpool.exec-slots.account=4096 --txpool.nonexec-slots.acc
ount=4096 --maxconnections=10 --multichannel
```

**Comment by aidan-kwon** [comment]
@YuXiaoCoder You can execute stateDB pruning following the instruction ins the link, https://docs.klaytn.foundation/content/operation-guide/chaindata-migration . Be aware that the pruning can be executed during node synchronization but it can cause out-of-memory issues. 
Another option is just downloading pruned chaindata from https://packages.klaytn.net/cypress/chaindata/

**Comment by YuXiaoCoder** [comment]
@aidan-kwon I wanted to enable the new version of --state.live-pruning and used the pruned snapshot, and it ran with the following errors
```log
/opt/klaymain/core/ken --cypress --datadir=/mnt/klaymain/node --syncmode=full --gcmode=archive --state.live-pruning --rpc --rpcaddr=0.0.0.0 --rpcport=8545 --rpcapi=klay,admin,eth,net,web3,debug --rpccorsdomain=* --rpcvhosts=* --port=30303 --srvtype=http --verbosity=3 --txpool.exec-slots.all=4096 --txpool.nonexec-slots.all=4096 --txpool.exec-slots.account=4096 --txpool.nonexec-slots.account=4096 --maxconnections=10 --multichannel --autorestart.enable

Fatal: Error starting protocol stack: cannot enable live pruning after chain has advanced
```

**Comment by aidan-kwon** [comment]
@YuXiaoCoder live-pruning and state migration I mentioned are different. The live-pruning feature requires a special data structure, so it is not compatible with the database of normal full or archive nodes. 
Please follow the state migration guide I linked in the above comment

**Comment by aidan-kwon** [comment]
Close this since there are no further questions.

**Comment by icculp** [comment]
Since that state migration guide is linked everywhere, but doesn't work, maybe y'all could add in some redirects when you break your docs like that.......
