### ISSUE TITLE
After upgrading to version 1.11.0, the block synchronization failed

### ISSUE THREAD

**Issue by coinbase-op** [klaytn/klaytn#2003]
root@2512544:/klay/kend start

docker logs -f klay
-----------------------------------------------------
INFO[10/20,02:25:31 Z] [5] Inserted a new block                      number=135456921 hash=b73a94…70b1e0                                                      txs=3  gas=454708  elapsed=28.218ms    processTxs=5.078ms   finalize=5.150ms   validateState=385.311µs totalWrite=15.774325ms trieWrite=15.521445ms
INFO[10/20,02:25:32 Z] [48] There is already corresponding badblock in db.  badblock number=135456922
ERROR[10/20,02:25:32 Z] [5] ########## BAD BLOCK ######### Chain config: {ChainID: 8217 IstanbulCompatibleBlock: 86816005 LondonCompatibleBlock: 86816005 EthTxTypeCompatibleBlock: 86816005 MagmaCompatibleBlock: 99841497 KoreCompatibleBlock: 119750400 ShanghaiCompatibleBlock: <nil> KIP103CompatibleBlock: 119750400 KIP103ContractAddress 0xD5ad6D61Dd87EdabE2332607C328f5cc96aeCB95 SubGroupSize: 31 UnitPrice: 250000000000 DeriveShaImpl: 0 Engine: istanbul} Number: 135456922 Hash: 0x891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e Receipt:    0: tx: 0xb6f658ef90399b4972dba2fda7c23bc627b445a453d2cd76b948fbd91bcd0099 status: 1 gas: 2034349 contract: 0x0000000000000000000000000000000000000000 bloom: 00000000000000000000001200000004000000000000000400000000000000001000000000020000100000000000000000000000101000000000000000000000000000000000000000200008000000040000000068101000100000000000000000000000020000000000000000000800000000000000100001000010000000200000000000000000000000000000000020000000000000000000000000000000000000000000000000010000000000000000008000000000000000000000004000000002000000000000000000000000000000000000000000000000040020000000000000000000600000000000000000000000000000000000000000000000 logs: [log: 268cc8248ffb72cd5f3e73a9a20fa2ff40efba61 [ef277373d709abc6be9d4926ac62b54991f4de2b6f8718079ae3d735ded22340 000000000000000000000000da39f11b50b31e7b48e110b2f5b283651965f17a] 000000000000000000000000000000000000000000000000000001d1a94e2606000000000000000000000000000000000000000000000000000001d1a94df78d000000000000000000000000000000000000000000000000000000e8d4a90ceb000029ceb31c040000628ca6100c421444314a2028c00180e72048101c2500ca000008c6338d4912944110ce39d24004aa28ce7000000014a3116b1154909c21 b6f658ef90399b4972dba2fda7c23bc627b445a453d2cd76b948fbd91bcd0099 0 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 0 log: 268cc8248ffb72cd5f3e73a9a20fa2ff40efba61 [ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0000000000000000000000000000000000000000000000000000000000000000 000000000000000000000000da39f11b50b31e7b48e110b2f5b283651965f17a 000000000000000000000000000000000000000000000000000001d1a94e2606]  b6f658ef90399b4972dba2fda7c23bc627b445a453d2cd76b948fbd91bcd0099 0 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 1 log: eb9ff38209dcc4236dbfb3c275c0aaeebf0b92cf [420fad2aa367fc1bd29a886c39c1d95207c9ba8213bba23045cbbcaa80b539df] 000000000000000000000000000000000000000000000000000001d1a94e26060000000000000000000000000000000000000000000000000000000000000001 b6f658ef90399b4972dba2fda7c23bc627b445a453d2cd76b948fbd91bcd0099 0 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 2 log: 268cc8248ffb72cd5f3e73a9a20fa2ff40efba61 [7be34da84992130f23438d167b22f7f7a246aaaf2d7e9dd3c988ee1672fe40fc 000000000000000000000000da39f11b50b31e7b48e110b2f5b283651965f17a] 000000000000000000000000000000000000000000000000000001d1a94e2606000000000000000000000000000000000000000000000000000001d1a94e260600000000000000000000000000000000000000000000000000000000652c9a8200000000000000000000000000000000000000000000000000000000652dec02000000000000000000000000000000000000000000000000000001d1a94df78d000000000000000000000000000000000000000000000000000000e8d4a90ceb00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000029ceb31c040000628ca6100c421444314a2028c00180e72048101c2500ca000008c6338d4912944110ce39d24004aa28ce7000000014a3116b1154909c21000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000013e00000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000b0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000d000000000000000000000000000000000000000000000000000000000000000b000000000000000000000000000000000000000000000000000000000000000900000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000069000000000000000000000000000000000000000000000000000000000000004600000000000000000000000000000000000000000000000000000000000000190000000000000000000000000000000000000000000000000000000000000bb80000000000000000000000000000000000000000000000000000000000001f400000000000000000000000000000000000000000000000000000000000001b5800000000000000000000000000000000000000000000000000000000000013880000000000000000000000000000000000000000000000000000000000000bb8000000000000000000000000000000000000000000000000000000000000157c000000000000000000000000000000000000000000000000000000000000157c0000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000000000000000000000000000000000dac0000000000000000000000000000000000000000000000000000000000000fa000000000000000000000000000000000000000000000000000000000000009c400000000000000000000000000000000000000000000000000000000000005dc0000000000000000000000000000000000000000000000000000000000000dac000000000000000000000000000000000000000000000000000000000000138800000000000000000000000000000000000000000000000000000000000002ee00000000000000000000000000000000000000000000000000000000000006d600000000000000000000000000000000000000000000000000000000000007d000000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000004e200000000000000000000000000000000000000000000000000000000000005dc000000000000000000000000000000000000000000000000000000000000047e000000000000000000000000000000000000000000000000000000000000036b00000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000002710000000000000000000000000000000000000000000000000000000000000177000000000000000000000000000000000000000000000000000000000000036b00000000000000000000000000000000000000000000000000000000000004e20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 b6f658ef90399b4972dba2fda7c23bc627b445a453d2cd76b948fbd91bcd0099 0 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 3 log: 13ce9c99e8e2fcde1632ada7b69b2ecf5be8ed45 [a6537abb32df743f25343a89920580e228e72ebe25cbbb40b6d83ce4aab0a425 000000000000000000000000da39f11b50b31e7b48e110b2f5b283651965f17a] 000000000000000000000000000000000000000000000000000001d1a94e023f000000000000000000000000000000000000000000000000000001d1a94e2606 b6f658ef90399b4972dba2fda7c23bc627b445a453d2cd76b948fbd91bcd0099 0 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 4]
         1: tx: 0xfed4d043531fe0d9961bd195498f9583c01394e491af5f7463f47bf822c2a309 status: 2 gas: 607320 contract: 0xe5CC5f00D2612baa0A7bAa43992cb4aA5184AF85 bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs: []
         2: tx: 0x172d96c9bb0737d0e70b05c873df187d5e3d3ed65b4cc342194b7e3e50dd09e7 status: 1 gas: 57414 contract: 0x0000000000000000000000000000000000000000 bloom: 08000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000010000000000000100000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000002000000000000000000000000000000000000200000000000000000000000000000000000002000000000000000000000000000000000000000000000 logs: [log: 1668e7c20df9d9675ceda3feae02eda06dd2d546 [ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0000000000000000000000002674e67b2e0c1c32eccc39b5c7fe7aaa4732395d 000000000000000000000000ac7cfb12b56fbbdaa39b576827a133ee00c4677d] 0000000000000000000000000000000000000000000000008ac7230489e80000 172d96c9bb0737d0e70b05c873df187d5e3d3ed65b4cc342194b7e3e50dd09e7 2 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 5]
         3: tx: 0xd8778dadd6ebe3cb0b9adf3bbcc701e85f1ccfc3d6ab4a7343dab3b08e9bb845 status: 1 gas: 75994 contract: 0x0000000000000000000000000000000000000000 bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000008000000000000000000100000000000000000000000100000000000000000000001000020000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000008000000000000000020000000000000000000000000000000000000000008000000000000080000000000 logs: [log: 63d4f17d2a8a729fd050f7679d961b1dfbb1e3af [c3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62 000000000000000000000000a7268405f4bbb1a7ff148182fa9e530c5775e363 0000000000000000000000000000000000000000000000000000000000000000 000000000000000000000000a7268405f4bbb1a7ff148182fa9e530c5775e363] 00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001 d8778dadd6ebe3cb0b9adf3bbcc701e85f1ccfc3d6ab4a7343dab3b08e9bb845 3 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 6]
         4: tx: 0x132b7bc4228a5972f1aafbc29c1632124564565999b5a4449463fb0ce72e4e67 status: 9 gas: 74038 contract: 0x0000000000000000000000000000000000000000 bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs: []
         5: tx: 0x9567bac6fe2b5f2a92fd28cae53e3f6bcc90ad5072c169179925b1cb41601d83 status: 1 gas: 184837 contract: 0x0000000000000000000000000000000000000000 bloom: 00000000200000000000000000000000000000000000000000000008000000000000000000000000000000000080020000000000000200000000000000000000000000000000000000000000002001000800000001000000000000000000000000000000000000000000000000000010000000000400000000000000100000000000000000000000000000000000000000000480000000000000000000020000000000001000000000000000000000000000000000000000000000000000000000000080000000000002000000000008000000000000000000000000000000000000000000000000100000000200000000000000000000000000000000000000 logs: [log: 955bd135abbc0eb0d022556602112a9ec456d41d [0109fc6f55cf40689f02fbaad7af7fe7bbac8a3d2186600afc7d3e10cac60271 000000000000000000000000000000000000000000000000000000000009bd2c 000000000000000000000000953903bc4036e1c803804e58813165c54aa9c3f7] 00000000000000000000000000000000000000000000000000000000652c9a82 9567bac6fe2b5f2a92fd28cae53e3f6bcc90ad5072c169179925b1cb41601d83 5 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 7 log: 955bd135abbc0eb0d022556602112a9ec456d41d [92e98423f8adac6e64d0608e519fd1cefb861498385c6dee70d58fc926ddc68c 0000000000000000000000000000000000000000000000000000000000c6e5f8 000000000000000000000000000000000000000000000000000000000009bd2c 000000000000000000000000953903bc4036e1c803804e58813165c54aa9c3f7]  9567bac6fe2b5f2a92fd28cae53e3f6bcc90ad5072c169179925b1cb41601d83 5 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 8 log: 955bd135abbc0eb0d022556602112a9ec456d41d [0559884fd3a460db3073b7fc896cc77986f16e378210ded43186175bf646fc5f 0000000000000000000000000000000000000000000000000000000000c6e5f8 000000000000000000000000000000000000000000000000000000000009bd2c] 00000000000000000000000000000000000000000000000000000000652c9a82 9567bac6fe2b5f2a92fd28cae53e3f6bcc90ad5072c169179925b1cb41601d83 5 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 9]
 Error: invalid gas used (remote: 2730292 local: 3033952)
WARN[10/20,02:25:32 Z] [28] Synchronisation failed, dropping peer     peer=612d7a88bad7b987 err="retrieved hash chain is invalid: invalid gas used (remote: 2730292 local: 3033952)"
WARN[10/20,02:25:32 Z] [33] ProtocolManager failed to read msg        id=612d7a88bad7b987 conn=trusted-staticdial err=EOF
WARN[10/20,02:25:32 Z] [33] ProtocolManager failed to read msg        id=612d7a88bad7b987 conn=trusted-staticdial err=EOF
INFO[10/20,02:25:32 Z] [33] Disconnected a multichannel P2P Peer      id=612d7a88bad7b987 conn=trusted-staticdial peerID=612d7a88bad7b987 peerName=Klaytn/v1.11.1/linux-amd64/go1.20.6 err=EOF
INFO[10/20,02:25:33 Z] [48] There is already corresponding badblock in db.  badblock number=135456922
ERROR[10/20,02:25:33 Z] [5] ########## BAD BLOCK ######### Chain config: {ChainID: 8217 IstanbulCompatibleBlock: 86816005 LondonCompatibleBlock: 86816005 EthTxTypeCompatibleBlock: 86816005 MagmaCompatibleBlock: 99841497 KoreCompatibleBlock: 119750400 ShanghaiCompatibleBlock: <nil> KIP103CompatibleBlock: 119750400 KIP103ContractAddress 0xD5ad6D61Dd87EdabE2332607C328f5cc96aeCB95 SubGroupSize: 31 UnitPrice: 250000000000 DeriveShaImpl: 0 Engine: istanbul} Number: 135456922 Hash: 0x891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e Receipt:    0: tx: 0xb6f658ef90399b4972dba2fda7c23bc627b445a453d2cd76b948fbd91bcd0099 status: 1 gas: 2034349 contract: 0x0000000000000000000000000000000000000000 bloom: 00000000000000000000001200000004000000000000000400000000000000001000000000020000100000000000000000000000101000000000000000000000000000000000000000200008000000040000000068101000100000000000000000000000020000000000000000000800000000000000100001000010000000200000000000000000000000000000000020000000000000000000000000000000000000000000000000010000000000000000008000000000000000000000004000000002000000000000000000000000000000000000000000000000040020000000000000000000600000000000000000000000000000000000000000000000 logs: [log: 268cc8248ffb72cd5f3e73a9a20fa2ff40efba61 [ef277373d709abc6be9d4926ac62b54991f4de2b6f8718079ae3d735ded22340 000000000000000000000000da39f11b50b31e7b48e110b2f5b283651965f17a] 000000000000000000000000000000000000000000000000000001d1a94e2606000000000000000000000000000000000000000000000000000001d1a94df78d000000000000000000000000000000000000000000000000000000e8d4a90ceb000029ceb31c040000628ca6100c421444314a2028c00180e72048101c2500ca000008c6338d4912944110ce39d24004aa28ce7000000014a3116b1154909c21 b6f658ef90399b4972dba2fda7c23bc627b445a453d2cd76b948fbd91bcd0099 0 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 0 log: 268cc8248ffb72cd5f3e73a9a20fa2ff40efba61 [ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0000000000000000000000000000000000000000000000000000000000000000 000000000000000000000000da39f11b50b31e7b48e110b2f5b283651965f17a 000000000000000000000000000000000000000000000000000001d1a94e2606]  b6f658ef90399b4972dba2fda7c23bc627b445a453d2cd76b948fbd91bcd0099 0 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 1 log: eb9ff38209dcc4236dbfb3c275c0aaeebf0b92cf [420fad2aa367fc1bd29a886c39c1d95207c9ba8213bba23045cbbcaa80b539df] 000000000000000000000000000000000000000000000000000001d1a94e26060000000000000000000000000000000000000000000000000000000000000001 b6f658ef90399b4972dba2fda7c23bc627b445a453d2cd76b948fbd91bcd0099 0 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 2 log: 268cc8248ffb72cd5f3e73a9a20fa2ff40efba61 [7be34da84992130f23438d167b22f7f7a246aaaf2d7e9dd3c988ee1672fe40fc 000000000000000000000000da39f11b50b31e7b48e110b2f5b283651965f17a] 000000000000000000000000000000000000000000000000000001d1a94e2606000000000000000000000000000000000000000000000000000001d1a94e260600000000000000000000000000000000000000000000000000000000652c9a8200000000000000000000000000000000000000000000000000000000652dec02000000000000000000000000000000000000000000000000000001d1a94df78d000000000000000000000000000000000000000000000000000000e8d4a90ceb00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000029ceb31c040000628ca6100c421444314a2028c00180e72048101c2500ca000008c6338d4912944110ce39d24004aa28ce7000000014a3116b1154909c21000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000013e00000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000b0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000d000000000000000000000000000000000000000000000000000000000000000b000000000000000000000000000000000000000000000000000000000000000900000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000007000000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000050000000000000000000000000000000000000000000000000000000000000069000000000000000000000000000000000000000000000000000000000000004600000000000000000000000000000000000000000000000000000000000000190000000000000000000000000000000000000000000000000000000000000bb80000000000000000000000000000000000000000000000000000000000001f400000000000000000000000000000000000000000000000000000000000001b5800000000000000000000000000000000000000000000000000000000000013880000000000000000000000000000000000000000000000000000000000000bb8000000000000000000000000000000000000000000000000000000000000157c000000000000000000000000000000000000000000000000000000000000157c0000000000000000000000000000000000000000000000000000000000000c800000000000000000000000000000000000000000000000000000000000000dac0000000000000000000000000000000000000000000000000000000000000fa000000000000000000000000000000000000000000000000000000000000009c400000000000000000000000000000000000000000000000000000000000005dc0000000000000000000000000000000000000000000000000000000000000dac000000000000000000000000000000000000000000000000000000000000138800000000000000000000000000000000000000000000000000000000000002ee00000000000000000000000000000000000000000000000000000000000006d600000000000000000000000000000000000000000000000000000000000007d000000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000004e200000000000000000000000000000000000000000000000000000000000005dc000000000000000000000000000000000000000000000000000000000000047e000000000000000000000000000000000000000000000000000000000000036b00000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000002710000000000000000000000000000000000000000000000000000000000000177000000000000000000000000000000000000000000000000000000000000036b00000000000000000000000000000000000000000000000000000000000004e20000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 b6f658ef90399b4972dba2fda7c23bc627b445a453d2cd76b948fbd91bcd0099 0 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 3 log: 13ce9c99e8e2fcde1632ada7b69b2ecf5be8ed45 [a6537abb32df743f25343a89920580e228e72ebe25cbbb40b6d83ce4aab0a425 000000000000000000000000da39f11b50b31e7b48e110b2f5b283651965f17a] 000000000000000000000000000000000000000000000000000001d1a94e023f000000000000000000000000000000000000000000000000000001d1a94e2606 b6f658ef90399b4972dba2fda7c23bc627b445a453d2cd76b948fbd91bcd0099 0 891dbf70dec251fb82cd8112b34920ff7d4baf54fa2251a42a6754280249230e 4]
         1: tx: 0xfed4d043531fe0d9961bd195498f9583c01394e491af5f7463f47bf822c2a309 status: 2 gas: 607320 contract: 0xe5CC5f00D2612baa0A7bAa43992cb4aA5184AF85 bloom: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by ian0371** [comment]
Hello, it seems that `ShanghaiCompatibleBlock` is not set because you're using v1.11.0.
Please try using v1.11.1 and see if the problem persists. Thanks.

**Comment by coinbase-op** [comment]
> Hello, it seems that `ShanghaiCompatibleBlock` is not set because you're using v1.11.0. Please try using v1.11.1 and see if the problem persists. Thanks.

@ian0371 
Thank you, after upgrading to 1.11.1, the blocks are synchronized.
