### ISSUE TITLE
Memory usage grows with no bounds

### ISSUE THREAD

**Issue by Lusitaniae** [klaytn/klaytn#2005]
**Describe the bug**
A "long" running node will grow memory usage until 100% of the node's capacity

**How to reproduce**
Run a node with some activity for a few days

**Expected behavior**
Memory usage is stable and within the advertised requirements (64Gb)

**Attachments**
![image](https://github.com/klaytn/klaytn/assets/58325/f6fae30c-76fc-4b2c-bb16-f72478162f07)

**Environment (please complete the following information)**
 - Klaytn v1.11.1+b131aece17
 - go version go1.20.4 linux/amd64
 - Ubuntu 20.04.6 LTS

**Additional context**
I see some old issues that have been closed, but the problem persists?

**Comment by yoomee1313** [comment]
Hi Lusitaniae, 64GB is a suggested memory size under normal condition. Depending on the load, the required memory size may vary.
Can you tell me the specific load or activity of your node? Also, do you run other node too? what about the node, do the other nodes experience similar problem?

**Comment by aidan-kwon** [comment]
@Lusitaniae Klaytn node sets a cache memory proportional to the machine's physical memory size. A node may set too much memory by default if you are running another process on the same machine. Is there any other heavy process running on the same machine?

**Comment by Lusitaniae** [comment]
Only have this klaytn node here

We don't have any other heavy processes, but we're running ZFS filesystem, guess it's also using a big "proportion" of available ram for caching

Maybe no reason for concern, I can open this issue again if I have more data

**Comment by aidan-kwon** [comment]
@Lusitaniae Thank you for sharing. If you want to control the usage of memory, you can manually configure the size of the largest cache. 
You can specify the cache size by adding a flag to the ADDITIONAL property in [the configuration file](https://docs.klaytn.foundation/content/operation-guide/configuration). If you want to set the cache size to 10240 MB (10GB), then you can specify it as the following. (I think 10GB setting will be okay for the node operation. The configuration could decrease block synchronization speed a little bit though)
```
--state.trie-cache-limit 10240
```

Please give more opinion if you found something more as you said. Thanks!
