### ISSUE TITLE
Update golang version in go.mod 1.18 -> 1.20

### ISSUE THREAD

**Issue by qezz** [klaytn/klaytn#2063]
**Describe the bug**
It doesn't build on go 1.18

**How to reproduce**

- go 1.18.10
- `make ken`

```
...
github.com/klaytn/klaytn/datasync/fetcher
github.com/klaytn/klaytn/consensus/gxhash
github.com/klaytn/klaytn/consensus/istanbul/core
github.com/klaytn/klaytn/node/cn/gasprice
util.go:60: exit status 2
exit status 1
make: *** [Makefile:22: ken] Error 1
```

**Expected behavior**
It compiles.
It does on go `1.20.10`

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - git revision - it's present on `dev`
 - `$ go version` - `go version go1.18.10 linux/amd64`
 - OS and its version - docker container with `ubuntu:20.04`

**Additional context**
n/a

**Comment by hyunsooda** [comment]
Hi @qezz, 

We should have updated the minimum go version properly. Should you compile with v1.20+ go binary, the build works.

**Comment by blukat29** [comment]
@qezz From v1.12.1 the minimum go version is raised to 1.20 in our `go.mod.`. Thanks for the report.
