### ISSUE TITLE
How to set up Klay EN Node locally using docker

### ISSUE THREAD

**Issue by mayank-daga** [klaytn/klaytn#2077]
Hi I want to know if there is way to set up Klay EndPoint Node(EN) via docker and using snapshot also. 
I know there is [non-docker](https://docs.klaytn.foundation/content/installation-guide/deployment/endpoint-node) set up but I am looking for Docker Approach to set up EN Node

**Comment by hyunsooda** [comment]
Hi, we are preparing docker-setup guide. For a while, you can refer a draft version below. If you encounter any issues, please let me know. Thank you.

https://github.com/klaytn/klaytn-docs/blob/docker-setup-guide/docs/installation-guide/deployment/endpoint-node/installation-guide/docker-setup.md

**Comment by mayank-daga** [comment]
Hi @hyunsooda this draft version will work fine right or there are some updates coming to this?

**Comment by hyunsooda** [comment]
Perhaps not at the moment, but we'll incorporate additional elements if necessary.
