### ISSUE TITLE
How can we get the internal transaction by querying Klaytn EN Node 

### ISSUE THREAD

**Issue by mayank-daga** [klaytn/klaytn#2087]
How can we get the internal transaction by querying Klaytn EN Node ?
I need the details for the rpc methods to be used

**Comment by hyunsooda** [comment]
Hi @mayank-daga,

`klay.getBlock() `retrieves a block with transaction hashes, which may be empty. For detailed transaction information, use `klay.getTransactionReceipt()`. I recommend you to explore the https://docs.klaytn.foundation/docs/references/json-rpc/klay/.

**Comment by mayank-daga** [comment]
Hi @hyunsooda klay.getTransactionReceipt() is not giving internal transaction (itx). I want internal transaction based on account directly

**Comment by hyunsooda** [comment]
Apologies for the confusion; I misunderstood that you were referring to blocking transactions.

To clarify, internal transactions are not standalone; they are essentially 'calls' within existing blocks. To establish the relationship between internal calls, two approaches can be considered:
1) Monitor the 'log' properties of the associated receipt. The log serves as proof of execution, and verifying a known log signature confirms the execution of the corresponding function.
2) Utilize `debug.traceTransaction()` to capture the `CALL` opcodes.

**Comment by mayank-daga** [comment]
closed
