### ISSUE TITLE
Getting Missing Trie Node Issue with Klaytn EN Node

### ISSUE THREAD

**Issue by mayank-daga** [klaytn/klaytn#2089]
I am giving below curl query but getting "message": "missing trie node 86fb9cd3b899c856281b04f8bb47e5757334cd7b8e683b5c503cfa97155acd3d (path )"

Curl Query:
curl --location 'node url' \
--header 'Content-Type: application/json' \
--data '{"jsonrpc":"2.0","method":"klay_getAccount","params":["0xBBdaD0e4326b01CE95d352E496A623De97e2763f", "0x8774E26"],"id":1}'

Note: The EN Node is setup using archival snapshot

**Comment by mayank-daga** [comment]
Hi @hyunsooda ,
I had set up EN Node using following steps and assumed this is archival only. Can you confirm if the steps are correct for archival node setup:  

1. [Download](http://content/installation-guide/deployment/endpoint-node/installation-guide/download) the latest version of the ken and other packers from Download page.
	Linux
	Cypress Packages
		• [ken-v1.11.1-0-linux-amd64.tar.gz](https://packages.klaytn.net/klaytn/v1.11.1/ken-v1.11.1-0-linux-amd64.tar.gz)
	Note: All the packages are downloaded in compressed file and we need to un-compress them.
	2. The installation is the uncompression of the downloaded package where you want to install the package
		sudo tar zxf ken-v1.11.1-0-linux-amd64.tar.gz
	Note: it is recommended that the uncompressed directory ken-linux-amd64/bin path should be added to the environment variable $PATH to run the ken and kend globally. As an example,
		export PATH=$PATH:/NewDisk116Machine/node-klay/ken-linux-amd64/bin
	3. Create a Data Directory
		sudo mkdir -p /node-klay/kend/data
	4. You should update the the data directory environment variable $DATA_DIR on the configuration file kend.conf.
		DATA_DIR=/node-klay/kend/data
	Note:  For the archive distribution, the config directory location defaults to $INSTALL_PATH/ken-linux-amd64/conf/.
	5. Download the latest chaindata snapshot from the [Cypress snapshot archive](http://packages.klaytn.net/cypress/chaindata/)
		sudo curl -o klaytn-cypress-chaindata-20231122011112.tar.gz "https://s3.ap-northeast-2.amazonaws.com/klaytn-chaindata/cypress/klaytn-cypress-chaindata-20231122011112.tar.gz"
	6. Before starting kend, extract the snapshot inside the DATA_DIR you configured in kend.conf.
	For example:
sudo tar -C /NewDisk116Machine/node-klay/kend/data -xvf klaytn-cypress-chaindata-20231218011212.tar.gz


**Note:** The data size of db is 3.1 Tb

**Comment by hyunsooda** [comment]
The snapshot archive you downloaded is a version of pruned chaindata. All the provided snapshots from the link only provide state-migrated snapshots (removed old states; not an archive).

**Comment by mayank-daga** [comment]
closed
