### ISSUE TITLE
Klaytn node don't return block 0x8650867 (140839015 in decimal)

### ISSUE THREAD

**Issue by nikolaikolosov** [klaytn/klaytn#2120]
**Bug description**
Can't receive the block 0x8650867 with using Klaytn RPC API. Blocks 0x8650866 and 0x8650868 could be received successfully.

**Steps to reproduce**
Make a request:
`curl -X POST http://KLAYTN_VALIDATOR_NODE_ADDRESS:KLAYTN_VALIDATOR_NODE_PORT -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"debug_traceBlockByNumber","params":["0x8650867",{"tracer":"callTracer","timeout":"120s"}],"id":4482549}'`

**Expected behavior**
Response with block content, same as for this request:
`curl -X POST https://archive-en.cypress.klaytn.net -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"debug_traceBlockByNumber","params":["0x8650867",{"tracer":"callTracer","timeout":"120s"}],"id":4482549}'`

**Actual behavior**
curl: (52) Empty reply from server

**Additional context**
I would like to understand, which node parameters I have to change to receive block 0x8650867? If it possible, I would like to get configuration of Klaytn node, which serves endpoint https://archive-en.cypress.klaytn.net

**Comment by hyunsooda** [comment]
Hi @nikolaikolosov,

The API faces limitations during heavy operations. Specifically, debug_traceBlockByNumber necessitates state regeneration, which is considered a resource-intensive task. Under standard settings, if regeneration exceeds 60 seconds, the API operation will not succeed, rendering the timeout option ineffective. However, if you are operating your own node, you have the option to adjust the regeneration time threshold, allowing for greater flexibility.

**Comment by blukat29** [comment]
It looks like this particular block has too many transactions to be processed at once.
Without changing the node configuration, you can use `debug_traceTransaction` for each txhash in the block and then merge them. Sorry for the inconvenience.

Please continue any further inquiries on https://github.com/kaiachain/kaia/issues.
