### ISSUE TITLE
EN node not syncing

### ISSUE THREAD

**Issue by aki263** [klaytn/klaytn#2138]
I downloaded latest EN snapshot as mentioned in https://docs.klaytn.foundation/docs/nodes/endpoint-node/docker-setup/.

Running this in ec2 instance that is in private subnet and has a nat gateway. 

> NETWORK="cypress"
NETWORK_ID="8217"
SERVER_TYPE="http"
SYNCMODE="full"
VERBOSITY=4
RPC_ENABLE=1
RPC_API="admin, debug, klay, miner, net, personal, rpc, txpool, web3"
RPC_ADDR="0.0.0.0"
RPC_VHOSTS="*"
WS_ENABLE=1
WS_API="admin, debug, klay, miner, net, personal, rpc, txpool, web3"
METRICS=1
PROMETHEUS=1
DATA_DIR=/var/kend/data
LOG_DIR=/var/kend/logs
ADDITIONAL="--upstream-en https://archive-en.cypress.klaytn.net"

Now I am getting error for new data to sync

> DEBUG[04/24,12:49:40 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:40 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:44 Z] [34] lookup                                    Discover=Simple   StorageName=PN targetId=0000000000000000 targetType=PN
DEBUG[04/24,12:49:44 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=2
DEBUG[04/24,12:49:44 Z] [33] [Dial] Add new discoverTypedStaticTask    name=PN
DEBUG[04/24,12:49:44 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=6e60f0c1bc397475 targetNodeType=EN refreshIfEmpty=true
DEBUG[04/24,12:49:44 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=1784e1423b4e4d19 targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:44 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:44 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=79ae1ba1165033c5 targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:44 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:44 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=dda0708192d1fc5c targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:44 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:44 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=5fd0d4ab8c40b662 targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:44 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:44 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:48 Z] [34] lookup                                    Discover=Simple   StorageName=PN targetId=0000000000000000 targetType=PN
DEBUG[04/24,12:49:48 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=2
DEBUG[04/24,12:49:48 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=d7ed59952ace3046 targetNodeType=EN refreshIfEmpty=true
DEBUG[04/24,12:49:48 Z] [33] [Dial] Add new discoverTypedStaticTask    name=PN
DEBUG[04/24,12:49:48 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=1784e1423b4e4d19 targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:48 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:48 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=3f776ba1bc045abb targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:48 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:48 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=d71b35e4ef501625 targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:48 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:48 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=150f121d75265e8e targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:48 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:48 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:52 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=048e1606ab66a254 targetNodeType=EN refreshIfEmpty=true
DEBUG[04/24,12:49:52 Z] [34] lookup                                    Discover=Simple   StorageName=PN targetId=0000000000000000 targetType=PN
DEBUG[04/24,12:49:52 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=2
DEBUG[04/24,12:49:52 Z] [33] [Dial] Add new discoverTypedStaticTask    name=PN
DEBUG[04/24,12:49:52 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=1784e1423b4e4d19 targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:52 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:52 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=f485c814806eb51d targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:52 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:52 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=57fcc6e7f3eb8008 targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:52 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:52 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=753586efe2d4a2b4 targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:52 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:52 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:53 Z] [28] Recalculated downloader QoS values        rtt=20s confidence=1.000 ttl=1m0s
DEBUG[04/24,12:49:56 Z] [34] lookup                                    Discover=Simple   StorageName=PN targetId=0000000000000000 targetType=PN
DEBUG[04/24,12:49:56 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=2
DEBUG[04/24,12:49:56 Z] [33] [Dial] Add new discoverTypedStaticTask    name=PN
DEBUG[04/24,12:49:56 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=1de7806311201f02 targetNodeType=EN refreshIfEmpty=true
DEBUG[04/24,12:49:56 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=1784e1423b4e4d19 targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:56 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:56 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=55ae005163d4d128 targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:56 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:56 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=4b185bd2d7a2b882 targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:56 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:56 Z] [34] lookup start                              Discover=Kademlia StorageName=EN targetID=0a46ecae95251ea1 targetNodeType=EN refreshIfEmpty=false
DEBUG[04/24,12:49:56 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3
DEBUG[04/24,12:49:56 Z] [34] findNewNode: found nodes                  Discover=Table    length=0 nodeType=3

**Comment by yoomee1313** [comment]
Could you share the output of `ps -ef | grep ken`? In addition, the level of the log you shared is `debug` level which is not an error. Can you share the entire log? (from the latest start to the current) Btw, have you checked the connection configurations and ken version? (static-nodes.json, NO_DISCOVERY option on kend.conf which will be converted into --nodiscover flag) 

You mentioned you are running in the private subnet. Please check the opened ports. For the node connection, you should open the node ports. The default port of klaytn node is 30303,30304 unless you configure your own klaytn node port.

**Comment by blukat29** [comment]
Hi, if the problem persists please raise an issue in https://github.com/kaiachain/kaia. Thanks.
