### ISSUE TITLE
Klaytn node does not keep up with the network

### ISSUE THREAD

**Issue by SwatGuard** [klaytn/klaytn#2216]
Klaytn node stopped syncing and after kend start it's not brining blocks as fast as before (about 18-40 blocks/minute vs 60 blocks/minute)

**How to reproduce**
Run a node
**Expected behavior**
The node should be able to keep up with the network

Tailing kend.out does not reveal any errors.

**Environment (please complete the following information)**
 - Klaytn version or git revision that exhibits the issue `$ ken version`
v1.12.1+4831f49bba
Ubuntu 20.04.06 - latest updates applied today
32 core cpu 128 gb of ram 7tb nvme

**Additional context**

**Comment by blukat29** [comment]
It could be that the block range you were syncing had many transactions, or the p2p peers are not sending the blocks as fast. You could try with the latest binary from https://github.com/kaiachain/kaia/releases/tag/v1.0.1, or manually increase state trie cache (`--state.trie-cache-limit`), increase the open file descriptor limit (`ulinit -n`).

If the problem persists, please continue any further inquiries on https://github.com/kaiachain/kaia/issues.
