### ISSUE TITLE
[IDE] Editor color

### ISSUE THREAD

**Issue by pjc0247** [klaytn/klaytn#282]
[Klaytn IDE](https://ide.klaytn.com/)

Hard to recognize the text is selected or not.
See:

![image](https://user-images.githubusercontent.com/1961216/66288416-17d58e00-e914-11e9-930c-25b429353f5e.png)

**Comment by aidan-kwon** [comment]
Thank you for the report. As far as I know, we don't have any plan to change the color scheme of Klaytn IDE, but I sent your suggestion to other developers in charge of "Klaytn IDE".

By the way, you better send e-mail to "developer@klaytn.com" if you have any issue about "Klaytn IDE".

**Comment by aidan-kwon** [comment]
@pjc0247 I am gonna close this issue. If you have more comments, please leave it here or send us through e-mail.
