### ISSUE TITLE
How about introduce KIP & KRC?

### ISSUE THREAD

**Issue by benjioh5** [klaytn/klaytn#358]
Like BIP and EIP, I think Klaytn needs KIP for managing issues and standards. Also, Importing EIP & BIP is needed for enhanced experience for Klaytn users.

**Comment by kjhman21** [comment]
@benjioh5 Thanks for the suggestion. We are trying to make such processes now, please wait little bit more. We will make that soon. Thanks! :)

**Comment by kjhman21** [comment]
@benjioh5 Thanks for waiting! we finally created KIP! If you have any idea to improve klaytn or its ecosystem, please visit it and contribute!

https://github.com/klaytn/kips
