### ISSUE TITLE
Block sealing failed and Failed to decode message from payload 

### ISSUE THREAD

**Issue by danielimkk** [klaytn/klaytn#415]
Please help.
I am trying to run a consensus node.
1) I`ve generated keys using kgen;
2) Created new account using kcn and specified datadir with generated keys in it;
3) But when I launch a consensus node right after mining starts, I get an error that says: 
`"Block sealing failed err=unauthorized"`,
`ERROR[12/05,08:28:06 Z] [25] Failed to decode message from payload address=0x00.... err="unauthorized address"`.

So the question is, How should I make this user authorized? Or what could be the cause of this issue?
Thank you.

**Comment by kjhman21** [comment]
Why are you trying to run a consensus node?
The authorization of consensus nodes is given only for members in Klaytn governance council.
If you want to run a full node, please use an endpoint node.

**Comment by danielimkk** [comment]
Thank you for answer. So operating a Core Cell is restricted, unless you are an invited entity?

**Comment by kjhman21** [comment]
For Baobab (testnet) and Cypress (mainnet), yes.

If you want to run your private network, you can do that. Please refer to https://docs.klaytn.com/node/service-chain/getting-started/4nodes-setup-guide.

**Comment by danielimkk** [comment]
Ok, thanks for helping.
