### ISSUE TITLE
Wrong information on Document. 

### ISSUE THREAD

**Issue by MegaSolar** [klaytn/klaytn#434]
Please see below links.

https://docs.klaytn.com/bapp/json-rpc/api-references/klay/transaction/transaction-type-support#txtypevaluetransfer

https://docs.klaytn.com/klaytn/design/transactions/basic#txtypevaluetransfer

I have compared both of documents, I don't know which docs would be right. 
I think ```TxTypeValueTransfer``` is for send klay. isnt' it?

**Comment by kjhman21** [comment]
Thanks for the issue. To clarify this, are you asking those statements?

- TxTypeValueTransfer is used when a user wants to send KLAY.
- TxTypeValueTransfer is used when a user wants to send tokens.

If it's right, yes, sending KLAY is the purpose of this transaction type. We will correct this soon.
Thanks.

**Comment by kjhman21** [comment]
@MegaSolar Now, it is fixed. Please refer to both URLs.
I will close this issue. If you think this is not resolved, please feel free to reopen this.
Thanks.
