### ISSUE TITLE
Question for using fee delegation account key among role based account key through caver-js for transaction. 

### ISSUE THREAD

**Issue by MegaSolar** [klaytn/klaytn#437]
Network : Baobab. 
node version:  v10.16.0
role based account : *0x2a43b52cb061ed8becbdeaebbe9bbe428cdef5fa*

code below. 
```
const Caver = require('caver-js')
const caver = new Caver('http://localhost:8551/')

async function testFunction() {
// I added role based account key for fee delegation. 

const Rolebasedccount = caver.klay.accounts.wallet.add('0x45d21e794938c32a2bc94de5f3249525c4f9cb5a7fbcd66b994edfa25f7086eb','0x2a43b52cb061ed8becbdeaebbe9bbe428cdef5fa')
}
 const sendAcc = caver.klay.accounts.wallet.add('0xsend account private key');

const tx = {
        type: 'FEE_DELEGATED_VALUE_TRANSFER',
        from : sendAcc.address,
        to :'0xc8c5c552a7505073a88590bb2970c3f70ac0a7d3',
        gas : '300000',
        value : '123000000000000000',
    }
 const senderRawTransaction = await caver.klay.accounts.signTransaction(tx,sendAcc.privateKey)

 const fee_delegation_tx = {
        type: 'FEE_DELEGATED_VALUE_TRANSFER',
        from : sendAcc.address,
        to :'0xc8c5c552a7505073a88590bb2970c3f70ac0a7d3',
        gas : '300000',
        value : '123000000000000000',
        signatures:[[senderRawTransaction.v,senderRawTransaction.r,senderRawTransaction.s]]
    }

const fee_delegation_tx_res = await caver.klay.accounts.feePayerSignTransaction(fee_delegation_tx,'0x45d21e794938c32a2bc94de5f3249525c4f9cb5a7fbcd66b994edfa25f7086eb')

 console.log(fee_delegation_tx_res)

 const send_tx = await caver.klay.sendTransaction({
        senderRawTransaction:fee_delegation_tx_res,
        feePayer:Rolebasedccount.address
    })

console.log(send_tx)

```

result 

```
{ messageHash:
   '0x36e510a2529944c4875783db1058f0578cd5b54038cc772cdd8e8957d2e553a0',
  v: '0x07f6',
  r:
   '0x3cd93f03ea9b652f9ba9e1c206a06842641fc2e7ecbc044178ce41a3cc3db80e',
  s:
   '0x1f8571efd6dbdd8baa284443be35e31e60fcb78690994710ee7ce521311b6a17',
  rawTransaction:
   '0x09f8e5028505d21dba00830493e094c8c5c552a7505073a88590bb2970c3f70ac0a7d38801b4fbd92b5f8000944bf3b787e9d07fd3e974a62ab341eb6a4d7b0f35f847f8458207f5a02def1b7ddd86321df1edc97dec603924c57855cc2e700ebeb7aa3b65e1769997a039424473ef416d103568d36e68cf9aca482221a0d938651ccf320044c57cae8a942a43b52cb061ed8becbdeaebbe9bbe428cdef5faf847f8458207f6a03cd93f03ea9b652f9ba9e1c206a06842641fc2e7ecbc044178ce41a3cc3db80ea01f8571efd6dbdd8baa284443be35e31e60fcb78690994710ee7ce521311b6a17',
  txHash:
   '0xd0e69fd63c5ba92011c627cd4596861ffa8cd94a19f2ffa6acb01cbed2635402',
  senderTxHash:
   '0xc12dd1286010f5958e14d135b39145efb742c697296b24e35bc09506adbfa469',
  feePayerSignatures:
   [ [ '0x07f6',
       '0x3cd93f03ea9b652f9ba9e1c206a06842641fc2e7ecbc044178ce41a3cc3db80e',
       '0x1f8571efd6dbdd8baa284443be35e31e60fcb78690994710ee7ce521311b6a17' ] ] }

(node:31122) UnhandledPromiseRejectionWarning: Error: Invalid raw Tx
    at Object.getTxTypeStringFromRawTransaction (/home/docker/node/node_modules/caver-js/packages/caver-utils/src/utils.js:660:51)
    at splitFeePayer (/home/docker/node/node_modules/caver-js/packages/caver-klay/caver-klay-accounts/src/makeRawTransaction.js:229:30)
    at Accounts.signTransaction (/home/docker/node/node_modules/caver-js/packages/caver-klay/caver-klay-accounts/src/index.js:641:76)
    at /home/docker/node/node_modules/caver-js/packages/caver-core-method/src/index.js:330:26
    at Object.getGasPrice [as callback] (/home/docker/node/node_modules/caver-js/packages/caver-core-method/src/index.js:409:9)
    at /home/docker/node/node_modules/caver-js/packages/caver-core-method/src/index.js:255:35
    at /home/docker/node/node_modules/caver-js/packages/caver-core-requestmanager/src/index.js:162:17
    at XMLHttpRequest.request.onreadystatechange (/home/docker/node/node_modules/caver-js/packages/caver-core-requestmanager/caver-providers-http/src/index.js:112:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/docker/node/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/docker/node/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
```

why I got Invalid Raw Tx return? 
anybody knows why?

testFunction()

**Comment by MegaSolar** [comment]
Dev team will give me detail instruction for fee delegate tx type instruction would be appreciated.

**Comment by kjhman21** [comment]
@jimni1222 Could you please answer to this question?

**Comment by jimni1222** [comment]
@MegaSolar 
Hi :) Let me briefly explain how to use the fee delegated tx type.

There are several ways for fee payers to sign transactions using caver.klay.accounts.feePayerSignTransaction.
Here I will explain how the fee payer signs after the transaction sender signs it.

1. Sign the transaction by passing as a parameter an RLP-encoded transaction string containing the sender's signature.
2. Sign the transaction by sending as a parameter a transaction object with the sender's signature defined

Note that both caver.klay.accounts.signTransaction (second parameter) and caver.klay.accounts.feePayerSignTransaction (third parameter) do not need to pass the key to be used as a signature if an account has been added to the in-memory wallet.

I modified it a bit to make the code work based on the example you wrote above.

In the example below, testFunction corresponds to item 2 above and testFunction2 corresponds to item 1 above.

If you can get an RLP-encoded transaction string containing the sender's signature, you don't need to create a new transaction object for fee payer, so i want to recommend you implementing it like testFunction2.

And caver.klay.sendTransaction signs the received transaction and sends it to the node.
If you have already signed a transaction, use caver.klay.sendSignedTransaction.

// TestFunction -> Sign the transaction by sending as a parameter a transaction object with the sender's signature defined
`
async function testFunction() {
    // I added role based account key for fee delegation.

    const rolebased_account = caver.klay.accounts.wallet.add('0x{fee payer key of rolebased account}', '0x{address of fee payer}')
    const send_acc = caver.klay.accounts.wallet.add('0x{key of sender}')

    const tx = {
        type: 'FEE_DELEGATED_VALUE_TRANSFER',
        from: send_acc.address,
        to: '0xc8c5c552a7505073a88590bb2970c3f70ac0a7d3',
        gas: '300000',
        value: caver.utils.toPeb(1, 'KLAY'),
	}
	
	// You don't have to send key parameter, when you added account to in-memory wallet
	const sender_signed = await caver.klay.accounts.signTransaction(tx)
	
	// In sender_signed, rawTransaction property will be RLP-encoded transaction string. This RLP-encoded string will include signatures of sender
	// And in sender_signed, signatures property will be signatures of sender
	console.log(sender_signed)

	// You can sign transaction with transaction object which includes sender's signatures like below
	// But if you can get rawTransaction
    const tx_for_fee_payer = Object.assign({ signatures: sender_signed.signatures }, tx)

	// The second parameter of feePayerSignTransaction should be address of fee payer
	// You added fee payer account to in-memory wallet, so you don't have to send third parameter which means key to sign
    const fee_payer_signed = await caver.klay.accounts.feePayerSignTransaction(tx_for_fee_payer, rolebased_account.address)

    console.log(fee_payer_signed)

    const send_tx_receipt = await caver.klay.sendSignedTransaction(fee_payer_signed)

    console.log(send_tx_receipt)
}
`

// TestFunction2 -> Sign the transaction by passing as a parameter an RLP-encoded transaction string containing the sender's signature
`
async function testFunction2() {
    // I added role based account key for fee delegation.

    const rolebased_account = caver.klay.accounts.wallet.add('0x{fee payer key of rolebased account}', '0x{address of fee payer}')
    const send_acc = caver.klay.accounts.wallet.add('0x{key of sender}')

    const tx = {
        type: 'FEE_DELEGATED_VALUE_TRANSFER',
        from: send_acc.address,
        to: '0xc8c5c552a7505073a88590bb2970c3f70ac0a7d3',
        gas: '300000',
        value: caver.utils.toPeb(1, 'KLAY'),
	}
	
	// You don't have to send key parameter, when you added account to in-memory wallet
	const sender_signed = await caver.klay.accounts.signTransaction(tx)
	
	// In sender_signed, rawTransaction property will be RLP-encoded transaction string. This RLP-encoded string will include signatures of sender
	// And in sender_signed, signatures property will be signatures of sender
	console.log(sender_signed)

	// You can sign transaction as a fee payer with RLP-encoded transaction string parameter which includes signatures of sender
    const fee_payer_signed = await caver.klay.accounts.feePayerSignTransaction(sender_signed.rawTransaction, rolebased_account.address)

    console.log(fee_payer_signed)

    const send_tx_receipt = await caver.klay.sendSignedTransaction(fee_payer_signed)

    console.log(send_tx_receipt)
}
`

If you are having trouble with the above example, please tell me.
If you have an issue with using caver-js, please leave your issue in caver-js's repository for quicker answers :)

I hope my answer was helpful.

(https://github.com/klaytn/caver-js/issues)

**Comment by KimKyungup** [comment]
Thanks for the report and answer. 
I close this Issue. 
If you need, please feel free to reopen this or make a topic in [https://klaytn.discourse.group/](https://klaytn.discourse.group/).
