### ISSUE TITLE
When will the next release of the node?

### ISSUE THREAD

**Issue by Jongsic** [klaytn/klaytn#443]
Ken node fall into panic during processing rpc request.  `(debug_traceBlockByNumber - {tracer: "callTracer"})`

This problem happens many times on a day, and happens EVERYDAY.
and Today is more serious .

this cause syncing delay, and then node has more and more load.

I need that rpc method to trace internal assets(KLAY, KCT) sended action during contract execution.
Is there other way to detect internal sending action?

AFAIK i have no way to solve this problrm.

When will the next release of the node?

**Comment by KimKyungup** [comment]
@Jongsic In #432 , I fixed the issue with a PR.
Our team will release next version in April. 
The release will include improved PR.

Thanks for your report.
If you have any question, please feel free to make a topic in [https://klaytn.discourse.group/](https://klaytn.discourse.group) also.
