### ISSUE TITLE
Problem with BadgerDB version when using Klaytn and IPFS

### ISSUE THREAD

**Issue by xlab** [klaytn/klaytn#450]
Hello, there is not a bug but a very unfortunate state of things about Klaytn's dependency on `github.com/dgraph/badger` of version `v1.5.4`. Newer versions of badger provide a slightly different API for setting and getting values.

Example:
```
../../../../pkg/mod/github.com/klaytn/klaytn@v1.3.0/storage/database/badger_database.go:137:26: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
../../../../pkg/mod/github.com/klaytn/klaytn@v1.3.0/storage/database/badger_database.go:149:2: not enough arguments to return
	have (error)
	want ([]byte, error)
../../../../pkg/mod/github.com/klaytn/klaytn@v1.3.0/storage/database/badger_database.go:149:19: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
```

Usually this is avoided by tweaking `go.mod` so it will include `v1.5.4` explicitly and that would be enough, e.g. https://github.com/kompose-app/klaybook/blob/master/go.mod#L6

But when there are additional IPFS dependencies, it will require `github.com/dgraph-io/badger v1.6.0` explicitly, which breaks Klaytn!

Example:
```
github.com/ipfs/go-ds-badger v0.0.4 // indirect
```

The improvement would be to migrate at least on the latest stable version of badger such as `v1.6.0`.

**Comment by xlab** [comment]
Quick hack that helps:

```
replace (
	github.com/dgraph-io/badger => github.com/dgraph-io/badger v1.5.4
)
```

(i.e. place that dep into `replace` instead of `require`)

**Comment by KimKyungup** [comment]
@xlab The above PR was merged. :)
Thanks for letting me know.
