### ISSUE TITLE
Update project status badges

### ISSUE THREAD

**Issue by smseo** [klaytn/klaytn#451]
**Is your request related to a problem? Please describe.**
If Klaytn's README uses various badges for the project development status, it would be great.

**Describe the solution you'd like**
I'd like to suggest two enhancements:
1. Use a badge for pkg.go.dev instead of godoc.org
   1. As described on https://blog.golang.org/pkg.go.dev-2020, godoc.org requests will be redirected to pkg.go.dev
   1. There's not an official badge for pkg.go.dev yet, but we can use one suggested at https://github.com/golang/go/issues/36982
1. Add a badge for go report card
   1. https://goreportcard.com/report/github.com/klaytn/klaytn
   1. [![Go Report Card](https://goreportcard.com/badge/github.com/klaytn/klaytn)](https://goreportcard.com/report/github.com/klaytn/klaytn)
      1. It seems gofmt is not working correctly?

**Comment by smseo** [comment]
@KimKyungup @kjhman21  Can someone investigate why gofmt and golint failed to run tests in https://goreportcard.com/report/github.com/klaytn/klaytn ? As far as I know, they used to succeed on https://goreportcard.com/.

**Comment by KimKyungup** [comment]
https://github.com/gojp/goreportcard/issues/303
There is same issue. Well. I will find the solution.

**Comment by KimKyungup** [comment]
It was resolved.

**Comment by KimKyungup** [comment]
A badge for go report card looks good now. So I will consider to update the badge.
