### ISSUE TITLE
Parity for Klaytn?

### ISSUE THREAD

**Issue by anhcao142** [klaytn/klaytn#455]
Probably not the right repo but can you build something like Parity but for Klaytn. Usually, I would use Parity to trace ETH transfer in a smart contract transfer transaction. In Klaytn, although you can transfer Klay using smart contract, there currently no easy method to query such transaction (e.g. how many KLAY is sent to which address?).

**Comment by kjhman21** [comment]
@anhcao142 
Thanks for filing an issue!

It seems that you need a functionality in Parity, not whole feature of Parity. Could you explain what function do you want to use?

**Comment by KimKyungup** [comment]
@anhcao142 Could you please tell us the feature you need?

**Comment by anhcao142** [comment]
Hi @kjhman21 @KimKyungup I currently need the `trace_replayBlockTransactions` api feature in ETH Parity

**Comment by KimKyungup** [comment]
@anhcao142 Please consider below API.
https://docs.klaytn.com/bapp/json-rpc/api-references/debug/tracing#debug_traceblock.

I think this API is similar with `trace_replayBlockTransactions` in parity.

**Comment by anhcao142** [comment]
We already took a look at the API, but still haven't able to produce the result as from `trace_replayBlockTransactions`. Anyway, thank you for the suggestion.
