### ISSUE TITLE
build execute file ,platform windows target linux ,occur this bug 

### ISSUE THREAD

**Issue by RustMann** [klaytn/klaytn#467]
**Describe the bug**
build execute file ,platform windows target linux ,occur this bug 
on windows cmd :
set GOOS=linux
go build -ldflags "-s -w"  , then occur
# github.com/klaytn/klaytn/crypto/secp256k1
G:\GoPath\pkg\mod\github.com\klaytn\klaytn@v1.3.0\crypto\secp256k1\schnorr.go:27:27: undefined: BitCurve
G:\GoPath\pkg\mod\github.com\klaytn\klaytn@v1.3.0\crypto\secp256k1\schnorr.go:63:8: undefined: ScMul
G:\GoPath\pkg\mod\github.com\klaytn\klaytn@v1.3.0\crypto\secp256k1\schnorr.go:64:7: undefined: ScSub
G:\GoPath\pkg\mod\github.com\klaytn\klaytn@v1.3.0\crypto\secp256k1\schnorr.go:71:23: undefined: BitCurve
G:\GoPath\pkg\mod\github.com\klaytn\klaytn@v1.3.0\crypto\secp256k1\schnorr.go:164:35: undefined: BitCurve
G:\GoPath\pkg\mod\github.com\klaytn\klaytn@v1.3.0\crypto\secp256k1\schnorr.go:172:6: undefined: ScMul
G:\GoPath\pkg\mod\github.com\klaytn\klaytn@v1.3.0\crypto\secp256k1\schnorr.go:187:9: undefined: ScSub
G:\GoPath\pkg\mod\github.com\klaytn\klaytn@v1.3.0\crypto\secp256k1\schnorr.go:187:18: undefined: ScMul

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.

**Environment (please complete the following information)**
 - Klaytn version or git revision that exhibits the issue `$ ken v1.3.0`
 - go version `$ go 1.41`
 - OS and its version [window10]

**Additional context**

**Comment by aidan-kwon** [comment]
@RustMann Since some packages in Klaytn uses `cgo`, you need to enable cgo and specify a C cross-compiler as follows.
```
set CGO_ENABLED=1
set CC=[c cross compiler]
set GOOS=linux
set GOARCH=amd64
```

Or you can use docker with a Linux image. In that case, you can build more easily with `Makefile`. 
I am sorry for that Klaytn doesn't provide build scripts for Windows environments.

**Comment by aidan-kwon** [comment]
I close this issue. @RustMann if my comment was not enough to resolve your problem, please make another issue.
