### ISSUE TITLE
노드가 잘 구동되다가 멈춰버립니다.

### ISSUE THREAD

**Issue by blockchen-admin** [klaytn/klaytn#967]
마지막 블럭까지 정상적으로 동기화가 끝난이후에
1~2시간 정도 구동시키면 노드가 멈춰버립니다.
RPC API도 호출이안되고 ken 프로그램이 멈춰버립니다.

OS : 우분투 20.04
CPU : AMD 에픽 7742
RAM : 32GB
SSD : INTEL PCIE NVME P4618 6.4TB

**Comment by KimKyungup** [comment]
혹시 top 명령어로 cpu, memroy 사용량 확인을 해보실까요?
완전 멈춘것으로 보이시면 kill -3 [process id]를 통해서 callstack이있는 로그를 공유해주시면 이슈파악에 도움이 될것 같습니다.
감사합니다.
@blockchen-admin

**Comment by blockchen-admin** [comment]
kill -3 을 해도 덤프 파일 저장이 안됩니다.

**Comment by KimKyungup** [comment]
저 상태에서 아래와 같이 실행하시면 standard output으로 출력이 됩니다. 한번 확인부탁드립니다.
`kill -3 328796`

그리고 v1.6.1에 cpu 사용량 이슈가 발견되어 hotfix로 v1.6.2를 릴리즈 하였으나 참조 부탁드립니다.

**Comment by KimKyungup** [comment]
혹시 attach를 해보셨는지요?
attach가 되신다면 `debug.verbosity(5)` 이렇게 log level을 올려서 log가 올라오는지 확인해보면 좋겠습니다.
https://docs.klaytn.com/getting-started/quick-start/top-up-your-account#attaching-to-the-console

**Comment by blockchen-admin** [comment]
1.6.2 버전으로 업데이트이후 24시간동안 해당 문제없이 정상적으로 구동되는게 확인됬습니다.
감사합니다.

@KimKyungup

**Comment by KimKyungup** [comment]
@blockchen-admin 확인해주셔서 감사합니다. 또 혹시 이슈 있으시면 레포트 해주십시요.
