### ISSUE TITLE
Why can't this data be downloaded completely? 440G files can only be downloaded 399g

### ISSUE THREAD

**Issue by ghost** [klaytn/klaytn#973]
Why can't this data be downloaded completely? 440G files can only be downloaded 399g？

I've tried to download it twice, both times

![image](https://user-images.githubusercontent.com/46479118/118927736-cd801400-b974-11eb-8cf3-99d5aaa99774.png)

**Comment by laurelgithub** [comment]
I downloaded it from  ‘https://packages.klaytn.net/cypress/chaindata/’.

**Comment by TN8ru5omyg2kf94j6SH7DyEENPJkFY2ftZ** [comment]
ÚDT

**Comment by aidan-kwon** [comment]
@laurelgithub @phuongtayga Sorry for the late response. 
Do you still have the same issue? I tried it on my PC and it has worked. 
Please, let me know if you have the same issue. (I will response quickly in the next time)
